#!/usr/bin/env bun
/**
 * Audit what the app can actually answer, and turn the gaps into the ustadz's worklist.
 *
 * WHY THIS EXISTS. Erik asked whether the routing fixes meant the "homoseksual" and "siapa Allah"
 * hiccups were behind us. The honest answer was that two anecdotes are not coverage, and the only
 * way to know was to measure. This runs the real lanes — feeling retrieval, reviewed aqidah, the
 * scholar's topical index — over a corpus of questions we expect to be asked, and reports which
 * ones land.
 *
 * IT DELIBERATELY DOES NOT GRADE ANSWER QUALITY. It reports which LANE answered and with what,
 * because that is mechanically checkable. Whether an answer is theologically right is the ustadz's
 * call, and pretending a script can score it would be the same over-reach this whole app exists to
 * avoid.
 *
 * Two outputs:
 *   docs/review/coverage-audit.md   — the measurement, per question and in totals
 *   docs/review/ustadz-worklist.md  — what he needs to author, ordered by expected demand
 *
 *   bun run app:coverage-audit
 */
import { DEMO_QUESTIONS, type DemoQuestion } from "./demo-questions.ts";

// The lanes fetch their shards by URL; serve them from the built output instead of a server.
// Typed without DOM lib types: this runs under the root tsconfig, which has no DOM — the whole
// reason peta-data.ts exists. `unknown` keeps it honest rather than reaching for `any`.
globalThis.fetch = (async (input: unknown) => {
  const u = String(input);
  const path = `web/public${u.startsWith("/") ? u : `/${u}`}`;
  const text = await Bun.file(path).text();
  return { ok: true, json: async () => JSON.parse(text) };
}) as unknown as typeof fetch;

const { retrieveKnowledge } = await import("../../web/src/knowledge.ts");
const { AQIDAH, isReviewed, matchAqidah } = await import("../../web/src/aqidah.ts");
const { retrieve } = await import("../../web/src/retrieve.ts");
const { looksFactual, knowledgeOnly } = await import("../../web/src/question-form.ts");

const corpus = JSON.parse(await Bun.file("web/public/corpus.json").text());

type Lane = "AQIDAH" | "INDEX" | "FEELING" | "POINTER" | "SILENCE";
interface Row extends DemoQuestion {
  lane: Lane;
  detail: string;
  category: string | null;
}

/** Mirrors the resolve order in main.ts / demo.ts. If those change, this must change with them. */
async function resolve(q: string): Promise<Omit<Row, keyof DemoQuestion>> {
  if (looksFactual(q)) {
    const aq = matchAqidah(q);
    if (aq) return { lane: "AQIDAH", detail: aq.id, category: null };
    const k = await retrieveKnowledge(q);
    if (k && k.entries.length > 0)
      return { lane: "INDEX", detail: `${k.entries.length} entri`, category: k.category };
    // Only shapes where a feeling answer would be WRONG stop here; how-to questions fall through.
    if (knowledgeOnly(q)) {
      if (k) return { lane: "POINTER", detail: "tidak ada entri spesifik", category: k.category };
      return { lane: "SILENCE", detail: "tidak ada apa pun", category: null };
    }
  }
  const hits = retrieve(corpus, q, 2, []) as { verse: { ref: string } }[];
  if (hits.length > 0)
    return { lane: "FEELING", detail: hits.map((h) => h.verse.ref).join(", "), category: null };

  const k = await retrieveKnowledge(q);
  if (k && k.entries.length > 0)
    return { lane: "INDEX", detail: `${k.entries.length} entri`, category: k.category };
  if (k) return { lane: "POINTER", detail: "tidak ada entri spesifik", category: k.category };
  return { lane: "SILENCE", detail: "tidak ada apa pun", category: null };
}

const rows: Row[] = [];
for (const dq of DEMO_QUESTIONS) rows.push({ ...dq, ...(await resolve(dq.q)) });

const ANSWERED = new Set<Lane>(["AQIDAH", "INDEX", "FEELING"]);
const answered = rows.filter((r) => ANSWERED.has(r.lane));
const gaps = rows.filter((r) => !ANSWERED.has(r.lane));
const pct = (n: number): string => `${((n / rows.length) * 100).toFixed(0)}%`;

const tally = new Map<Lane, number>();
for (const r of rows) tally.set(r.lane, (tally.get(r.lane) ?? 0) + 1);

const byKind = new Map<string, { total: number; ok: number }>();
for (const r of rows) {
  const e = byKind.get(r.kind) ?? { total: 0, ok: 0 };
  e.total += 1;
  if (ANSWERED.has(r.lane)) e.ok += 1;
  byKind.set(r.kind, e);
}

const LANE_LABEL: Record<Lane, string> = {
  AQIDAH: "Jawaban akidah (ditinjau ustadz)",
  INDEX: "Entri Indeks Tematik",
  FEELING: "Ayat dari jalur perasaan",
  POINTER: "Hanya penunjuk kategori",
  SILENCE: "Tidak ada jawaban",
};

// ── coverage-audit.md ─────────────────────────────────────────────────────────────────────────
const audit = [
  `# Coverage audit`,
  ``,
  `> GENERATED by \`bun run app:coverage-audit\` — do not edit by hand.`,
  `> Corpus: \`src/review/demo-questions.ts\` (${rows.length} pertanyaan).`,
  ``,
  `Measures which LANE answers each question we expect to be asked. It does **not** grade whether`,
  `an answer is theologically correct — that is the reviewer's call, not a script's.`,
  ``,
  `## Totals`,
  ``,
  `| Hasil | Jumlah | Porsi |`,
  `| --- | ---: | ---: |`,
  ...(["AQIDAH", "INDEX", "FEELING", "POINTER", "SILENCE"] as Lane[]).map(
    (l) => `| ${LANE_LABEL[l]} | ${tally.get(l) ?? 0} | ${pct(tally.get(l) ?? 0)} |`,
  ),
  ``,
  `**Terjawab: ${answered.length}/${rows.length} (${pct(answered.length)}). Belum: ${gaps.length} (${pct(gaps.length)}).**`,
  ``,
  `## Per jenis pertanyaan`,
  ``,
  `| Jenis | Terjawab | Total | Porsi |`,
  `| --- | ---: | ---: | ---: |`,
  ...[...byKind]
    .sort((a, b) => a[1].ok / a[1].total - b[1].ok / b[1].total)
    .map(([k, v]) => `| ${k} | ${v.ok} | ${v.total} | ${((v.ok / v.total) * 100).toFixed(0)}% |`),
  ``,
  `## Setiap pertanyaan`,
  ``,
  `| Pertanyaan | Jenis | Hasil | Keterangan |`,
  `| --- | --- | --- | --- |`,
  ...rows.map(
    (r) =>
      `| ${r.q} | ${r.kind} | ${LANE_LABEL[r.lane]} | ${r.category ? `${r.category} — ` : ""}${r.detail} |`,
  ),
  ``,
].join("\n");

await Bun.write("docs/review/coverage-audit.md", audit);

// ── ustadz-worklist.md ────────────────────────────────────────────────────────────────────────
const unreviewedAqidah = AQIDAH.filter((e) => !isReviewed(e));
const byWeight = (a: Row, b: Row): number => b.weight - a.weight || a.q.localeCompare(b.q);
const pointerGaps = gaps.filter((r) => r.lane === "POINTER").sort(byWeight);
const silentGaps = gaps.filter((r) => r.lane === "SILENCE").sort(byWeight);

const worklist = [
  `# Daftar kerja untuk Ustadz Ahmad Isrofiel Mardlatillah`,
  ``,
  `> GENERATED by \`bun run app:coverage-audit\` — do not edit by hand.`,
  `> Diukur dari ${rows.length} pertanyaan yang kami perkirakan ditanyakan pengguna.`,
  ``,
  `Aplikasi menjawab **${answered.length} dari ${rows.length}** pertanyaan (${pct(answered.length)}).`,
  `Sisanya **${gaps.length}** belum ada jawabannya — bukan karena salah arah, tetapi karena`,
  `bahannya memang belum ada. Berikut bahan yang kami mohon kesediaan Ustadz untuk menuliskannya.`,
  ``,
  `Urutannya mengikuti perkiraan seberapa sering pertanyaan itu muncul.`,
  ``,
  `---`,
  ``,
  `## 1. Tujuh jawaban akidah — jalur ini belum bisa menjawab sama sekali`,
  ``,
  `Pertanyaan paling dasar (\`siapa Allah\`, \`di mana Allah\`, \`apa itu iman\`) belum terjawab sama`,
  `sekali. Aplikasi sudah mengenali pertanyaannya dan kami sudah mengusulkan ayat rujukannya,`,
  `tetapi jawabannya sengaja kami kosongkan: hanya kalimat Ustadz yang boleh tampil di jalur ini.`,
  `Selama masih kosong, aplikasi memilih diam.`,
  ``,
  `| # | Pertanyaan | Ayat yang kami usulkan | Catatan kami |`,
  `| --- | --- | --- | --- |`,
  ...unreviewedAqidah.map(
    (e, i) =>
      `| ${i + 1} | ${e.question} | ${e.suggestedRefs.map((r) => `QS ${r.surah}:${r.ayah}`).join(", ")} | ${e.note ?? "—"} |`,
  ),
  ``,
  `> Usulan ayat di atas adalah usulan kami, bukan ketetapan. Mohon diganti bila kurang tepat.`,
  ``,
  `---`,
  ``,
  `## 2. Topik yang ada kategorinya, tetapi belum ada entri spesifik (${pointerGaps.length})`,
  ``,
  `Untuk pertanyaan ini aplikasi menemukan bab yang tepat di Indeks Tematik, tetapi belum ada`,
  `baris yang menjawab pokok pertanyaannya. Yang tampil hanya kalimat penunjuk: *"Aku belum punya jawaban`,
  `ringkas yang sudah ditinjau untuk pertanyaan seluas itu."*`,
  ``,
  `| Pertanyaan | Kategori yang ditemukan |`,
  `| --- | --- |`,
  ...pointerGaps.map((r) => `| ${r.q} | ${r.category ?? "—"} |`),
  ``,
  `---`,
  ``,
  `## 3. Tidak ada apa pun (${silentGaps.length})`,
  ``,
  `Tidak ada kategori, tidak ada ayat, tidak ada entri. Aplikasi diam sepenuhnya.`,
  ``,
  `| Pertanyaan | Jenis |`,
  `| --- | --- |`,
  ...silentGaps.map((r) => `| ${r.q} | ${r.kind} |`),
  ``,
  `---`,
  ``,
  `## Yang TIDAK kami minta`,
  ``,
  `Jalur perasaan sudah berjalan baik dan sudah Ustadz tinjau pada 2026-07-22 (147 penempatan).`,
  `Kami tidak meminta tambahan di sana. Permintaan kami terbatas pada pertanyaan yang sifatnya`,
  `*pengetahuan* — "apa itu X", "siapa X", "apa hukum X" — yang justru paling sering diketik orang`,
  `saat pertama kali mencoba aplikasi.`,
  ``,
].join("\n");

await Bun.write("docs/review/ustadz-worklist.md", worklist);

console.log(
  `✓ audit    ${answered.length}/${rows.length} answered (${pct(answered.length)}), ${gaps.length} gaps ` +
    `→ docs/review/coverage-audit.md + docs/review/ustadz-worklist.md`,
);
for (const [k, v] of [...byKind].sort((a, b) => a[1].ok / a[1].total - b[1].ok / b[1].total)) {
  console.log(`    ${k.padEnd(8)} ${String(v.ok).padStart(3)}/${String(v.total).padEnd(3)} ${((v.ok / v.total) * 100).toFixed(0)}%`);
}
