/** Original QuranKu surah names + Indonesian meanings (scraped from the live site for fidelity). */
export const SURAH_ID: Record<number, [string, string]> = {
  1: ["Al-Fatihah", "Pembukaan"],
  2: ["Al-Baqarah", "Sapi Betina"],
  3: ["Ali 'Imran", "Keluarga Imran"],
  4: ["An-Nisa", "Wanita"],
  5: ["Al-Ma'idah", "Jamuan (Hidangan Makanan)"],
  6: ["Al-An'am", "Binatang Ternak"],
  7: ["Al-A'raf", "Tempat-tempat Tinggi"],
  8: ["Al-Anfal", "Rampasan Perang"],
  9: ["At-Tawbah", "Pengampunan"],
  10: ["Yunus", "Yunus"],
  11: ["Hud", "Hud"],
  12: ["Yusuf", "Yusuf"],
  13: ["Ar-Ra'd", "Guruh (Petir)"],
  14: ["Ibrahim", "Ibrahim"],
  15: ["Al-Hijr", "Bukit"],
  16: ["An-Nahl", "Lebah Madu"],
  17: ["Al-Isra", "Perjalanan Malam"],
  18: ["Al-Kahf", "Para Penghuni Gua"],
  19: ["Maryam", "Maryam"],
  20: ["Taha", "Tha-Ha"],
  21: ["Al-Anbya", "Para Nabi"],
  22: ["Al-Hajj", "Haji"],
  23: ["Al-Mu'minun", "Orang-orang Mukmin"],
  24: ["An-Nur", "Cahaya"],
  25: ["Al-Furqan", "Pembeda"],
  26: ["Ash-Shu'ara", "Penyair"],
  27: ["An-Naml", "Semut"],
  28: ["Al-Qasas", "Kisah-kisah"],
  29: ["Al-'Ankabut", "Laba-laba"],
  30: ["Ar-Rum", "Bangsa Romawi"],
  31: ["Luqman", "Luqman"],
  32: ["As-Sajdah", "Sujud"],
  33: ["Al-Ahzab", "Golongan yang Bersekutu"],
  34: ["Saba", "Saba'"],
  35: ["Fatir", "Pencipta"],
  36: ["Ya-Sin", "Yas Sin"],
  37: ["As-Saffat", "Barisan-barisan"],
  38: ["Sad", "Shad"],
  39: ["Az-Zumar", "Para Rombongan"],
  40: ["Ghafir", "Sang Maha Pengampun"],
  41: ["Fussilat", "Yang Dijelaskan"],
  42: ["Ash-Shuraa", "Musyawarah"],
  43: ["Az-Zukhruf", "Perhiasan"],
  44: ["Ad-Dukhan", "Kabut"],
  45: ["Al-Jathiyah", "Yang Bertekuk Lutut"],
  46: ["Al-Ahqaf", "Bukit-bukir Pasir"],
  47: ["Muhammad", "Muhammad"],
  48: ["Al-Fath", "Kemenangan"],
  49: ["Al-Hujurat", "Kamar-kamar"],
  50: ["Qaf", "Qaf"],
  51: ["Adh-Dhariyat", "Angin yang Menerbangkan"],
  52: ["At-Tur", "Bukit"],
  53: ["An-Najm", "Bintang"],
  54: ["Al-Qamar", "Bulan"],
  55: ["Ar-Rahman", "Yang Maha Pemurah"],
  56: ["Al-Waqi'ah", "Hari Kiamat"],
  57: ["Al-Hadid", "Besi"],
  58: ["Al-Mujadila", "Wanita yang Menggugat"],
  59: ["Al-Hashr", "Pengusiran"],
  60: ["Al-Mumtahanah", "Wanita yang Diuji"],
  61: ["As-Saf", "Barisan"],
  62: ["Al-Jumu'ah", "Hari Jum'at"],
  63: ["Al-Munafiqun", "Kaum Munafik"],
  64: ["At-Taghabun", "Hari Dinampakkan Kesalahan"],
  65: ["At-Talaq", "Perceraian"],
  66: ["At-Tahrim", "Mengharamkan"],
  67: ["Al-Mulk", "Kerajaan"],
  68: ["Al-Qalam", "Pena"],
  69: ["Al-Haqqah", "Kenyataan (Hari Kiamat)"],
  70: ["Al-Ma'arij", "Tempat yang Naik"],
  71: ["Nuh", "Nuh"],
  72: ["Al-Jinn", "Jin"],
  73: ["Al-Muzzammil", "Orang yang Berselimut"],
  74: ["Al-Muddaththir", "Orang yang Berkemul"],
  75: ["Al-Qiyamah", "Hari Berbangkit"],
  76: ["Al-Insan", "Manusia"],
  77: ["Al-Mursalat", "Malaikat-malaikan yang Diutus"],
  78: ["An-Naba", "Berita Besar"],
  79: ["An-Nazi'at", "Malaikat yang Mencabut"],
  80: ["'Abasa", "Ia Bermuka Masam"],
  81: ["At-Takwir", "Menggulung"],
  82: ["Al-Infitar", "Terbelah"],
  83: ["Al-Mutaffifin", "Orang-orang Curang"],
  84: ["Al-Inshiqaq", "Terbelah"],
  85: ["Al-Buruj", "Gugusan Bintang"],
  86: ["At-Tariq", "Yang Datang di Malam Hari"],
  87: ["Al-A'la", "Yang Paling Tinggi"],
  88: ["Al-Ghashiyah", "Hari Pembalasan"],
  89: ["Al-Fajr", "Fajar"],
  90: ["Al-Balad", "Negeri"],
  91: ["Ash-Shams", "Matahari"],
  92: ["Al-Layl", "Malam"],
  93: ["Ad-Duhaa", "Waktu Dhuha"],
  94: ["Ash-Sharh", "Melapangkan"],
  95: ["At-Tin", "Buah Tin"],
  96: ["Al-'Alaq", "Segumpal Darah"],
  97: ["Al-Qadr", "Kemuliaan"],
  98: ["Al-Bayyinah", "Pembuktian"],
  99: ["Az-Zalzalah", "Kegoncangan"],
  100: ["Al-'Adiyat", "Berlari Kencang"],
  101: ["Al-Qari'ah", "Hari Kiamat"],
  102: ["At-Takathur", "Bermegah-megahan"],
  103: ["Al-'Asr", "Waktu Sore"],
  104: ["Al-Humazah", "Pengumpat"],
  105: ["Al-Fil", "Gajah"],
  106: ["Quraysh", "Suku Quraisy"],
  107: ["Al-Ma'un", "Barang yang Berguna"],
  108: ["Al-Kawthar", "Nikmat Berlimpah"],
  109: ["Al-Kafirun", "Orang-orang Kafir"],
  110: ["An-Nasr", "Pertolongan"],
  111: ["Al-Masad", "Gejolak Api (Sabut)"],
  112: ["Al-Ikhlas", "Ikhlash"],
  113: ["Al-Falaq", "Waktu Shubuh"],
  114: ["An-Nas", "Umat Manusia"],
};

/** Display name from the original (falls back to the given transliteration). */
export const idName = (n: number, fallback: string): string => SURAH_ID[n]?.[0] ?? fallback;
/** Indonesian meaning from the original ("" if unknown). */
export const idMeaning = (n: number): string => SURAH_ID[n]?.[1] ?? "";
