/**
 * Where a finished summary's FILES live, and how they are served back.
 *
 * The queue row says a summary exists; this module holds the thing a reader actually opens. R2
 * rather than `web/dist` for the same reason the recitation corpus is a bucket: `web/dist` is baked
 * at build time and uploaded by `wrangler deploy`, so anything the runner produced after the last
 * build could not be in it.
 *
 * ── THE SECURITY PROBLEM THIS MODULE EXISTS TO CONTAIN ──────────────────────────────────────────
 *
 * The runner uploads HTML. That HTML is generated by a language model that has just read a
 * transcript of a third party's video, on a VPS that also runs `yt-dlp` against the open internet.
 * Serving it from this app's own origin makes it same-origin with the reader's session: script in
 * it could not READ `__Host-qk_auth` (that cookie is HttpOnly) but it could ride it, issuing
 * authenticated same-origin requests as the reader.
 *
 * So the response carries a restrictive `Content-Security-Policy` that permits inline STYLE and
 * nothing else — no script, no frames, no outbound connections, no object embedding — plus
 * `nosniff`, plus `sandbox` so the document gets an opaque origin and is not same-origin with the
 * app at all. The slide is a static page of text; it has never needed script, and the day it does
 * is the day this decision should be re-argued rather than quietly relaxed.
 *
 * THE NAME ALLOWLIST IS NOT COSMETIC EITHER. A runner that could choose arbitrary keys could write
 * `../index.html`, or upload a `.js` this origin would then serve as script. So both the video id
 * and the file name are matched against exact patterns, and the content type is decided HERE from
 * the allowlisted name — never read from the upload's own `Content-Type` header, which is a claim
 * made by the uploader about its own bytes.
 */

/** The R2 binding. Optional everywhere, like `AUDIO`: absent → the artefact routes answer 404. */
export interface KajianArtifactEnv {
  // `| undefined` explicitly, not just `?`. Under `exactOptionalPropertyTypes` an optional property
  // and a present-but-undefined one are different types, and `Env` is the second kind.
  KAJIAN?: R2Bucket | undefined;
}

interface R2Bucket {
  get(key: string): Promise<R2ObjectBody | null>;
  put(key: string, value: ArrayBuffer | ReadableStream): Promise<unknown>;
}
interface R2ObjectBody {
  body: ReadableStream;
  size: number;
}

const VIDEO_ID = /^[A-Za-z0-9_-]{11}$/;

/**
 * What a runner may upload, and what each is served as.
 *
 * DELIBERATELY NOT AN EXTENSION MAP. An allowlist of whole NAMES means the bucket holds one known
 * set of files per video and an unexpected name is refused rather than stored — there is no
 * "any .html" rule for a mistake to slip through.
 */
const ARTIFACTS: Record<string, string> = {
  "slide.html": "text/html; charset=utf-8",
  "slide.png": "image/png",
  "short.m4a": "audio/mp4",
};

/** The one media type that gets script-free treatment; the others cannot execute anyway. */
const HTML = "text/html; charset=utf-8";

/**
 * Inline style only, in a document with an OPAQUE ORIGIN.
 *
 * `sandbox` leads, and it is the load-bearing directive. As a CSP directive it applies the iframe
 * sandbox flags to the document ITSELF — with no `allow-same-origin`, the page is not same-origin
 * with the app, so it cannot ride the reader's session even if every other directive here were
 * loosened later. Adding `allow-same-origin` or `allow-scripts` undoes this, in that order of harm.
 *
 * The rest is defence in depth: `default-src 'none'` already denies script, and `script-src 'none'`
 * says so out loud because a reader of a policy should not have to derive a denial from an absence.
 */
const SLIDE_CSP =
  "sandbox; default-src 'none'; style-src 'unsafe-inline'; img-src data:; font-src data:; " +
  "script-src 'none'; frame-ancestors 'self'; form-action 'none'; base-uri 'none'";

export function artifactContentType(name: string): string | null {
  return ARTIFACTS[name] ?? null;
}

/**
 * Build the storage key, or refuse.
 *
 * Both halves are matched against a pattern rather than sanitised. Stripping `..` out of a name is
 * a rule about what is DANGEROUS; matching `^[A-Za-z0-9_-]{11}$` is a rule about what is VALID, and
 * only the second kind cannot be out-thought by an encoding.
 */
export function artifactKey(videoId: string, name: string): string | null {
  if (!VIDEO_ID.test(videoId)) return null;
  if (artifactContentType(name) === null) return null;
  return `${videoId}/${name}`;
}

/** 24 MB. A slide is kilobytes and a short narration is under a megabyte; this is a bound on abuse,
 *  not a target. */
export const MAX_ARTIFACT_BYTES = 24 * 1024 * 1024;

/** The public URL a stored artefact is reachable at — the value that becomes `summaryUrl`. */
export function artifactPath(videoId: string, name: string): string {
  return `/kajian/${videoId}/${name}`;
}

/**
 * Parse `/kajian/{videoId}/{name}`.
 *
 * `/kajian/index.json` must NOT match: it is the published list, handled elsewhere, and it has only
 * two segments so it cannot. Stated because the two live under one prefix and a later widening of
 * this parser would silently capture it.
 */
export function parseArtifactPath(pathname: string): { videoId: string; name: string } | null {
  const parts = pathname.split("/").filter((p) => p !== "");
  if (parts.length !== 3 || parts[0] !== "kajian") return null;
  const videoId = parts[1];
  const name = parts[2];
  if (videoId === undefined || name === undefined) return null;
  if (artifactKey(videoId, name) === null) return null;
  return { videoId, name };
}

/** Serve one artefact, with the headers that make an uploaded document inert. */
export async function serveArtifact(
  env: KajianArtifactEnv,
  videoId: string,
  name: string,
): Promise<Response | null> {
  const bucket = env.KAJIAN;
  if (!bucket) return null;
  const key = artifactKey(videoId, name);
  if (key === null) return null;

  const object = await bucket.get(key);
  if (object === null) return null;

  const type = artifactContentType(name) ?? "application/octet-stream";
  const headers = new Headers({
    "Content-Type": type,
    // Decided here from the allowlisted name. `nosniff` then stops a browser overriding it with a
    // guess drawn from the bytes — which is how a text file becomes a script.
    "X-Content-Type-Options": "nosniff",
    // Immutable per video: a re-run writes a new summary for the same id only when an admin asks
    // for it, and a reader holding an hour-old copy of a lecture summary has lost nothing.
    "Cache-Control": "public, max-age=3600",
  });
  if (type === HTML) {
    // A first cut of this set a `Sandbox:` header, which is not an HTTP header at all — the sandbox
    // is a CSP DIRECTIVE, and it now leads SLIDE_CSP. The mistake is recorded because a header that
    // does nothing looks exactly like a header that works.
    headers.set("Content-Security-Policy", SLIDE_CSP);
    // Belt to the CSP's braces, for anything that predates `frame-ancestors`.
    headers.set("X-Frame-Options", "SAMEORIGIN");
  }
  return new Response(object.body, { status: 200, headers });
}
