#!/usr/bin/env bun
/**
 * Build the surah-introduction corpus (مقدمة السورة) — ARABIC, VERBATIM.
 *
 * SOURCE: `data/surah-intro-src/<nnn>.md` — the tafseer-okf export of Dorar Al-Saniyyah's
 * موسوعة التفسير surah prefaces, one markdown file per surah, YAML frontmatter + `##` sections.
 *
 * ── RIGHTS: READ THIS BEFORE CHANGING ANYTHING HERE ──────────────────────────────────────────
 *
 * The source record marks this content `usage: private` — "modern authored compilation, all
 * rights reserved; no licence published by the source", clearance path "written permission from
 * Dorar Al-Saniyyah". Erik decided on 2026-08-08 to ship it publicly anyway, with attribution,
 * accepting the clearance risk as the product owner. That decision is recorded here rather than
 * hidden, because `build-hadith.ts` in this same directory makes the OPPOSITE call for
 * sunnah.com's English ("NOT cleared for a public site") and a future reader is owed the reason
 * the two builders differ. It is a business risk knowingly taken, not an oversight.
 *
 * Consequences that are NOT optional, and that keep the risk reversible:
 *   - every shard carries `source.title` / `source.url` / `source.supervisor`, and the UI renders
 *     them with a link back to dorar.net. Attribution is part of the artifact, not decoration.
 *   - the corpus is a build artifact under `web/public/` (gitignored). Pulling the feature is one
 *     deleted directory plus a redeploy — no rewrite, no data surgery.
 *
 * ── WHY ARABIC ONLY ───────────────────────────────────────────────────────────────────────────
 *
 * The `id` export exists for exactly one surah and is `translation: ai`, `official: false`,
 * `review_status: unreviewed`, `reviewer_needed: "Ustadz Ahmad Isrofiel"`. That is our own machine
 * output carrying Dorar's name — misattribution, and it bypasses the scholar-review gate that
 * governs every other piece of religious content in this app. New-Quranku displays scholarship
 * verbatim and never authors it. So this build takes the Arabic Dorar actually wrote and ships
 * nothing else. A reviewed Indonesian edition is a later, gated step.
 *
 * ── BYTE-EXACT ARABIC ─────────────────────────────────────────────────────────────────────────
 *
 * Every Arabic string here is SLICED from the source file's bytes, never retyped — Arabic authored
 * by hand byte-differs from a corpus though it renders identically. Section headings are CLASSIFIED
 * by comparing a diacritic-stripped form against prefixes derived mechanically from the corpus
 * itself, and the emitted `title` is the untouched source heading. `JSON.stringify` preserves the
 * code points unchanged.
 *
 * OUTPUT (sharded like the hadith corpus, so a reader downloads only the surah they open):
 *   web/public/surah-intro/<n>.json   — one surah's preface
 *   web/public/surah-intro/index.json — which surahs have an intro, and their section counts
 *
 * Both are gitignored build artifacts, regenerated by `bun run build`.
 *
 *   bun run app:surah-intro
 */
import { Glob } from "bun";
import { mkdir } from "node:fs/promises";

const SRC = "data/surah-intro-src";
/** Alternate-language sources live at `<SRC_ALT>/<lang>/<nnn>.md`. Sparse by design — today only 1 of 114. */
const SRC_ALT = "data/surah-intro-src";
const ALT_LANGS = ["id"] as const;
const OUT_DIR = "web/public/surah-intro";
const EXPECTED_SURAHS = 114;

/** The kinds of section a Dorar preface is built from, in the order we render them. */
export type IntroKind = "names" | "revelation" | "aims" | "topics" | "virtues" | "other";

export interface IntroSection {
  readonly kind: IntroKind;
  /** The source heading, verbatim — we label sections in Dorar's words, not ours. */
  readonly title: string;
  /** The section prose, verbatim, footnote markers ([1], [2] …) intact. */
  readonly body: string;
}

/**
 * A non-Arabic edition of the same preface, offered as an OPTION beside the Arabic — never as a
 * replacement for it, and never unlabelled.
 *
 * The only edition that currently exists is an unreviewed machine translation. Its own source file
 * opens with `⚠ TERJEMAHAN AI, BELUM DITINJAU … Jangan disajikan ke pengguna sebelum ditinjau Ustadz
 * Ahmad Isrofiel`. Erik asked for it as a reader-selectable option on 2026-08-08, so it ships — but
 * the provenance fields below travel WITH the text and the renderer is required to display them,
 * because the failure that actually matters here is a reader mistaking machine output for Dorar's
 * scholarship. These fields are not metadata; they are part of the content.
 */
export interface IntroEdition {
  readonly lang: string;
  /** false for anything that is not an edition the rights holder published. */
  readonly official: boolean;
  /** e.g. "ai" — how the text came to exist. */
  readonly translation: string;
  /** e.g. "unreviewed". */
  readonly reviewStatus: string;
  /** Who still has to sign it off. */
  readonly reviewerNeeded: string;
  readonly sections: readonly IntroSection[];
  readonly refs: readonly string[];
}

export interface SurahIntro {
  readonly n: number;
  readonly nameAr: string;
  readonly lang: "ar";
  readonly source: {
    readonly title: string;
    readonly url: string;
    readonly supervisor: string;
  };
  readonly sections: readonly IntroSection[];
  /** The numbered المراجع list, one entry per footnote, verbatim. */
  readonly refs: readonly string[];
  /** Optional alternate editions, keyed by language. Absent when only the Arabic exists. */
  readonly editions?: Readonly<Record<string, IntroEdition>>;
}

/**
 * Arabic diacritics + tatweel. Stripped ONLY to compare headings against the classifier prefixes —
 * never applied to anything we emit. Covers the Qur'anic annotation blocks too, because Dorar's
 * headings are vocalised inconsistently across the 114 files (the same heading appears as both
 * `أسماء السورة` and `أسماءُ السُّورةِ`).
 */
const TASHKEEL = /[ؐ-ًؚ-ٰٟۖ-ۜ۟-۪ۨ-ۭـ]/g;

/**
 * Fold a heading to a comparable skeleton: drop diacritics, unify the alef and ya and ta-marbuta
 * variants, collapse whitespace. The prefixes below were produced by running this exact function
 * over all 114 source files and reading off the distinct results — they are not hand-typed Arabic.
 */
export const foldHeading = (s: string): string =>
  s
    .replace(TASHKEEL, "")
    .replace(/[آأإ]/g, "ا") // آ أ إ → ا
    .replace(/ى/g, "ي") // ى → ي
    .replace(/ة/g, "ه") // ة → ه
    .replace(/\s+/g, " ")
    .trim();

/**
 * Prefix → kind. Prefix rather than equality because two surahs name their own section
 * (`موضوعات سورة الأنعام`), and the virtues heading appears in three shapes
 * (`فضائل…`, `فضل السورة…`, `فضلها…`) that all share the same opening word stem.
 *
 * Order matters: `فضائل` and `فضل` both start with ف-ض-ل, so the longer prefix is tested first.
 */
const CLASSIFIERS: readonly (readonly [string, IntroKind])[] = [
  ["اسماء", "names"],
  ["بيان المكي", "revelation"],
  ["مقاصد", "aims"],
  ["موضوعات", "topics"],
  ["فضائل", "virtues"],
  ["فضل", "virtues"],
  // The Indonesian edition writes its headings in Indonesian. Matched lower-cased, and kept in the
  // same table so the two languages can never drift into different section vocabularies.
  ["nama-nama", "names"],
  ["penjelasan makkiyah", "revelation"],
  ["maksud-maksud", "aims"],
  ["tema-tema", "topics"],
  ["keutamaan", "virtues"],
];

/**
 * The heading whose section is the footnote apparatus, not prose.
 *
 * Prefix, not equality: the Indonesian edition keeps the Arabic word and glosses it —
 * `المراجع (Rujukan)` — so an exact match would silently render the whole footnote apparatus as
 * body prose.
 */
const REFS_HEADING = "المراجع";

/** Render order. `other` trails because it is the per-surah oddity, not part of the standard frame. */
const KIND_ORDER: readonly IntroKind[] = ["names", "revelation", "aims", "topics", "virtues", "other"];

export const classify = (heading: string): IntroKind | "references" => {
  const f = foldHeading(heading);
  if (f.startsWith(REFS_HEADING)) return "references";
  const lower = f.toLowerCase();
  for (const [prefix, kind] of CLASSIFIERS) if (f.startsWith(prefix) || lower.startsWith(prefix)) return kind;
  return "other";
};

/**
 * Read the scalar frontmatter fields we need.
 *
 * Deliberately NOT a YAML parser: the `rights:` block nests keys (`holder`, `basis`) that collide
 * with names we might later want at the top level, so we stop at the first indented line's parent
 * and only accept column-0 `key: value` pairs. Values may be quoted.
 */
export const frontmatter = (raw: string): Record<string, string> => {
  const m = /^---\n([\s\S]*?)\n---\n?/.exec(raw);
  if (!m) return {};
  const out: Record<string, string> = {};
  for (const line of m[1]!.split("\n")) {
    if (/^\s/.test(line)) continue; // nested — belongs to a block we do not read
    const kv = /^([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const v = kv[2]!.trim();
    if (v === "") continue; // a block opener like `rights:`
    out[kv[1]!] = v.replace(/^"(.*)"$/, "$1").replace(/^'(.*)'$/, "$1");
  }
  return out;
};

/** Strip the frontmatter and return the body only. */
const bodyOf = (raw: string): string => raw.replace(/^---\n[\s\S]*?\n---\n?/, "");

/**
 * Split `## ` sections. Returns [heading, body] pairs with the heading verbatim (trailing
 * whitespace trimmed — several source headings carry a stray space) and the body verbatim.
 */
export const sectionsOf = (body: string): readonly (readonly [string, string])[] => {
  const out: (readonly [string, string])[] = [];
  const lines = body.split("\n");
  let heading: string | null = null;
  let buf: string[] = [];
  const flush = (): void => {
    if (heading === null) return;
    out.push([heading, buf.join("\n").trim()] as const);
  };
  for (const line of lines) {
    if (line.startsWith("## ")) {
      flush();
      heading = line.slice(3).trim();
      buf = [];
    } else if (heading !== null) {
      buf.push(line);
    }
  }
  flush();
  return out;
};

/**
 * Split the المراجع body into its numbered entries.
 *
 * Entries open with `N. ` at the start of a line. A footnote can run to several lines, so we
 * accumulate until the next number opens. Numbering in the source is 1..N and contiguous; we keep
 * the text only and let the renderer supply the numerals, so a missing entry cannot silently
 * shift the ones after it — the assertion below catches that instead.
 */
export const splitRefs = (body: string): readonly string[] => {
  if (!body.trim()) return [];
  const out: string[] = [];
  let buf: string[] = [];
  for (const line of body.split("\n")) {
    const m = /^(\d+)\.\s+(.*)$/.exec(line);
    if (m) {
      if (buf.length) out.push(buf.join("\n").trim());
      buf = [m[2]!];
    } else if (buf.length) {
      buf.push(line);
    }
  }
  if (buf.length) out.push(buf.join("\n").trim());
  return out.filter((s) => s.length > 0);
};

/** Split a source file into its ordered prose sections and its footnote list. Language-agnostic. */
const partsOf = (raw: string): { sections: IntroSection[]; refs: readonly string[] } => {
  const sections: IntroSection[] = [];
  let refs: readonly string[] = [];
  for (const [title, body] of sectionsOf(bodyOf(raw))) {
    const kind = classify(title);
    if (kind === "references") {
      refs = splitRefs(body);
      continue;
    }
    if (!body) continue; // an empty section is nothing to show
    sections.push({ kind, title, body });
  }
  sections.sort((a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind));
  return { sections, refs };
};

/**
 * Parse an alternate-language edition.
 *
 * Refuses to emit one that does not declare its provenance. An edition whose `official`/`translation`
 * /`review_status` fields are missing cannot be labelled honestly downstream, and an unlabelled
 * machine translation of religious commentary is precisely the artifact this codebase must not ship.
 */
export const parseEdition = (raw: string, expectN: number, expectLang: string): IntroEdition => {
  const fm = frontmatter(raw);
  if (Number(fm["surah"]) !== expectN) throw new Error(`edition ${expectN}: frontmatter says surah=${fm["surah"]}`);
  if (fm["language"] !== expectLang) throw new Error(`edition ${expectN}: language=${fm["language"]}`);

  const official = fm["official"] === "true";
  const translation = fm["translation"] ?? "";
  const reviewStatus = fm["review_status"] ?? "";
  const reviewerNeeded = fm["reviewer_needed"] ?? "";
  if (!official && (!translation || !reviewStatus)) {
    throw new Error(
      `edition ${expectN} (${expectLang}): unofficial edition without translation/review_status — ` +
        `it cannot be labelled honestly, refusing to ship`,
    );
  }

  const { sections, refs } = partsOf(raw);
  if (!sections.length) throw new Error(`edition ${expectN} (${expectLang}): no sections parsed`);

  return { lang: expectLang, official, translation, reviewStatus, reviewerNeeded, sections, refs };
};

export const parseIntro = (raw: string, expectN: number): SurahIntro => {
  const fm = frontmatter(raw);
  const n = Number(fm["surah"]);
  if (n !== expectN) throw new Error(`surah ${expectN}: frontmatter says surah=${fm["surah"]}`);
  if (fm["language"] !== "ar") throw new Error(`surah ${expectN}: language=${fm["language"]}, expected ar`);

  const { sections, refs } = partsOf(raw);

  const nameAr = fm["surah_name"];
  const src = fm["source"];
  const url = fm["source_url"];
  const supervisor = fm["supervisor"];
  if (!nameAr || !src || !url || !supervisor) {
    throw new Error(`surah ${expectN}: incomplete attribution frontmatter — refusing to ship unattributed`);
  }

  return {
    n,
    nameAr,
    lang: "ar",
    source: { title: src, url, supervisor },
    sections,
    refs,
  };
};

// ── build ─────────────────────────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const files: string[] = [];
  for await (const f of new Glob("*.md").scan(SRC)) files.push(f);
  files.sort();

  if (files.length !== EXPECTED_SURAHS) {
    throw new Error(`expected ${EXPECTED_SURAHS} source files in ${SRC}, found ${files.length}`);
  }

  await mkdir(OUT_DIR, { recursive: true });

  const index: Record<number, number> = {};
  const altCount: Record<string, number> = {};
  let totalSections = 0;

  for (const f of files) {
    const n = Number(f.replace(/\.md$/, ""));
    if (!Number.isInteger(n) || n < 1 || n > 114) throw new Error(`bad source filename: ${f}`);

    const raw = await Bun.file(`${SRC}/${f}`).text();
    const intro = parseIntro(raw, n);

    // Every Dorar preface carries these three. A surah missing one means the parser drifted from
    // the source shape — fail the build rather than ship a preface with a hole in it.
    for (const required of ["names", "revelation", "aims"] as const) {
      if (!intro.sections.some((s) => s.kind === required)) {
        throw new Error(`surah ${n}: no "${required}" section — parser drift, refusing to write`);
      }
    }
    // Not fatal — one surah genuinely has a bespoke section — but it must be visible in the log so
    // a future source update cannot quietly reclassify half the corpus as "other".
    const odd = intro.sections.filter((s) => s.kind === "other").map((s) => s.title);
    if (odd.length) console.log(`  note: surah ${n} unclassified section(s): ${odd.join(" | ")}`);

    // Alternate editions, when one exists for this surah. Absent is the normal case today.
    const editions: Record<string, IntroEdition> = {};
    for (const lang of ALT_LANGS) {
      const f2 = Bun.file(`${SRC_ALT}/${lang}/${String(n).padStart(3, "0")}.md`);
      if (!(await f2.exists())) continue;
      editions[lang] = parseEdition(await f2.text(), n, lang);
      altCount[lang] = (altCount[lang] ?? 0) + 1;
    }

    const shard: SurahIntro = Object.keys(editions).length ? { ...intro, editions } : intro;
    await Bun.write(`${OUT_DIR}/${n}.json`, JSON.stringify(shard));
    index[n] = intro.sections.length;
    totalSections += intro.sections.length;
  }

  await Bun.write(`${OUT_DIR}/index.json`, JSON.stringify({ surahs: index }));

  console.log(
    `surah-intro: ${files.length} surahs, ${totalSections} sections → ${OUT_DIR}/ (Arabic, verbatim, Dorar-attributed)`,
  );
  for (const lang of ALT_LANGS) {
    const n = altCount[lang] ?? 0;
    // Loud on purpose. A 1-of-114 alternate edition is a scaffold, not a feature, and the gap is
    // the thing a reader will actually hit.
    console.log(`  alt edition "${lang}": ${n}/${EXPECTED_SURAHS} surahs${n < EXPECTED_SURAHS ? " — SPARSE" : ""}`);
  }
}
