#!/usr/bin/env bun
/**
 * Build the Hadis (Ṣaḥīḥayn) browse corpus — ARABIC ONLY.
 *
 * SOURCE: `data/hadith-src/` — the tafseer-okf Ṣaḥīḥayn export (Sahih al-Bukhari + Sahih Muslim,
 * 14,736 hadith), one markdown file per hadith at `<collection>/<book>/<bab>/<num>.md` with a YAML
 * frontmatter and two body sections: `## العربية` and `## English`.
 *
 * WHY ARABIC ONLY. The Arabic of the two Ṣaḥīḥs is the canonical ~1200-year-old text — public
 * domain, byte-preserved from the source. The English body is a sunnah.com edition (Muhsin Khan et
 * al.) whose source record is licensed "private research use" — NOT cleared for a public site. So
 * this build takes the Arabic and our own structural metadata (collection, kitab, bab, number,
 * grade, source link) and DROPS the English translation and the English narrator line entirely.
 * New-Quranku displays scholarship verbatim and never authors religious content; shipping the
 * canonical Arabic with honest sourcing honours that, while a licensed Indonesian translation is a
 * later, gated step. (See the "displaying others' scholarship" + content-pillars notes.)
 *
 * BYTE-EXACT ARABIC. The Arabic is SLICED from the source file's bytes, never retyped — Arabic I
 * author byte-differs from a corpus though it renders identically. The extractor takes the exact
 * substring under `## العربية`; JSON.stringify preserves the code points unchanged.
 *
 * OUTPUT (sharded like the Peta Tematik corpus, so a reader loads only the kitab they open):
 *   web/public/hadith/index.json              — collections + their kitab list (small; fetched once)
 *   web/public/hadith/<collection>/<book>.json — one kitab: its babs, each with its hadith
 *
 * Both are gitignored build artifacts (like corpus.json / juz.json), regenerated by `bun run build`.
 *
 *   bun run app:hadith
 */
import { Glob } from "bun";

const SRC = "data/hadith-src";
const OUT_DIR = "web/public/hadith";

/** The two collections we ship, in reading order. Ids are the source dir names + the route segment. */
const COLLECTIONS = [
  { id: "bukhari", name: "Sahih al-Bukhari", nameAr: "صحيح البخاري" },
  { id: "muslim", name: "Sahih Muslim", nameAr: "صحيح مسلم" },
] as const;

const EXPECTED_TOTAL = 14736;

interface Hadith {
  readonly n: number; // hadith_number
  readonly grade: string;
  readonly ar: string; // byte-exact Arabic
  readonly url: string; // sunnah.com attribution link
}

interface Bab {
  readonly no: number;
  readonly ar: string;
  hadith: Hadith[];
}

interface Book {
  readonly no: number;
  readonly ar: string;
  authorAr: string;
  readonly babs: Map<number, Bab>;
}

/** One frontmatter value by key. Values may be quoted or bare; we only need scalar strings/ints. */
function fm(front: string, key: string): string | undefined {
  const m = front.match(new RegExp(`^${key}:[ \\t]*(.*)$`, "m"));
  if (!m || m[1] === undefined) return undefined;
  let v = m[1].trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1);
  }
  return v;
}

function intFm(front: string, key: string, ctx: string): number {
  const raw = fm(front, key);
  if (raw === undefined || raw === "") throw new Error(`${ctx}: missing "${key}"`);
  const n = Number(raw);
  if (!Number.isInteger(n)) throw new Error(`${ctx}: "${key}" not an integer: ${raw}`);
  return n;
}

function strFm(front: string, key: string, ctx: string): string {
  const raw = fm(front, key);
  if (raw === undefined || raw === "") throw new Error(`${ctx}: missing "${key}"`);
  return raw;
}

/**
 * Slice the Arabic body — the exact substring under `## العربية`, up to the next `## ` heading (the
 * English section) or end of file. Never retyped; byte-preserved from source.
 */
function extractArabic(text: string, ctx: string): string {
  const start = text.indexOf("## العربية");
  if (start < 0) throw new Error(`${ctx}: no "## العربية" section`);
  const after = start + "## العربية".length;
  const nextHeading = text.indexOf("\n## ", after);
  const body = nextHeading < 0 ? text.slice(after) : text.slice(after, nextHeading);
  const ar = body.trim();
  if (ar.length === 0) throw new Error(`${ctx}: empty Arabic body`);
  return ar;
}

async function buildCollection(id: string, name: string, nameAr: string): Promise<{
  meta: { id: string; name: string; name_ar: string; author_ar: string; hadith: number; books: Array<{ no: number; ar: string; hadith: number; babs: number }> };
  shards: Array<{ book: number; payload: unknown }>;
}> {
  const dir = `${SRC}/${id}`;
  const books = new Map<number, Book>();
  let count = 0;

  const glob = new Glob("*/*/*.md");
  for await (const rel of glob.scan(dir)) {
    const path = `${dir}/${rel}`;
    const text = await Bun.file(path).text();
    const fmMatch = text.match(/^---\n([\s\S]*?)\n---\n/);
    if (!fmMatch || fmMatch[1] === undefined) throw new Error(`${path}: no frontmatter`);
    const front = fmMatch[1];
    const ctx = path;

    const bookNo = intFm(front, "book", ctx);
    const bookAr = strFm(front, "book_ar", ctx);
    const babNo = intFm(front, "bab", ctx);
    // bab_ar is occasionally empty — a handful of chapter headings are Qur'anic phrases the source
    // carries only in English. We never invent an Arabic title; such babs simply render untitled.
    const babAr = fm(front, "bab_ar") ?? "";
    const n = intFm(front, "hadith_number", ctx);
    const grade = strFm(front, "grade", ctx);
    const url = strFm(front, "source_url", ctx);
    const authorAr = strFm(front, "author_ar", ctx);
    const ar = extractArabic(text, ctx);

    let book = books.get(bookNo);
    if (!book) {
      book = { no: bookNo, ar: bookAr, authorAr, babs: new Map() };
      books.set(bookNo, book);
    }
    let bab = book.babs.get(babNo);
    if (!bab) {
      bab = { no: babNo, ar: babAr, hadith: [] };
      book.babs.set(babNo, bab);
    }
    bab.hadith.push({ n, grade, ar, url });
    count += 1;
  }

  if (count === 0) throw new Error(`${dir}: no hadith found`);

  const sortedBooks = [...books.values()].sort((a, b) => a.no - b.no);
  const authorAr = sortedBooks[0]?.authorAr ?? "";
  const metaBooks: Array<{ no: number; ar: string; hadith: number; babs: number }> = [];
  const shards: Array<{ book: number; payload: unknown }> = [];

  for (const book of sortedBooks) {
    const sortedBabs = [...book.babs.values()].sort((a, b) => a.no - b.no);
    let bookHadith = 0;
    const babsPayload = sortedBabs.map((bab) => {
      const hadith = [...bab.hadith].sort((a, b) => a.n - b.n);
      bookHadith += hadith.length;
      return { no: bab.no, ar: bab.ar, hadith };
    });
    metaBooks.push({ no: book.no, ar: book.ar, hadith: bookHadith, babs: sortedBabs.length });
    shards.push({
      book: book.no,
      payload: {
        collection: name,
        collection_ar: nameAr,
        book: { no: book.no, ar: book.ar },
        babs: babsPayload,
      },
    });
  }

  return {
    meta: { id, name, name_ar: nameAr, author_ar: authorAr, hadith: count, books: metaBooks },
    shards,
  };
}

async function main(): Promise<void> {
  // Wipe stale shards so a renamed/removed kitab can't linger.
  await Bun.$`rm -rf ${OUT_DIR}`.quiet();

  const collectionsMeta: unknown[] = [];
  let total = 0;

  for (const c of COLLECTIONS) {
    const { meta, shards } = await buildCollection(c.id, c.name, c.nameAr);
    total += meta.hadith;
    collectionsMeta.push(meta);
    for (const { book, payload } of shards) {
      await Bun.write(`${OUT_DIR}/${c.id}/${book}.json`, `${JSON.stringify(payload)}\n`);
    }
    console.log(`  ${c.name}: ${meta.hadith} hadith, ${meta.books.length} kitab → ${OUT_DIR}/${c.id}/`);
  }

  if (total !== EXPECTED_TOTAL) {
    throw new Error(`hadith total ${total} ≠ expected ${EXPECTED_TOTAL} — source changed or a file was skipped`);
  }

  const index = {
    source:
      "Ṣaḥīḥayn — Sahih al-Bukhari & Sahih Muslim, Arabic (canonical, public domain). Structural " +
      "metadata + attribution links via sunnah.com. Translations withheld pending licensing.",
    note: "Arabic-only. New-Quranku displays scholarship verbatim; a licensed Indonesian translation is a later, reviewed step.",
    total,
    collections: collectionsMeta,
  };
  await Bun.write(`${OUT_DIR}/index.json`, `${JSON.stringify(index, null, 2)}\n`);

  console.log(`hadith: ${total} hadith across ${COLLECTIONS.length} collections → ${OUT_DIR}/`);
}

await main();
