#!/usr/bin/env bun
/**
 * Build the theme index — Path A from issue 07 (`.scratch/nur-phase2-trust-and-depth/issues/
 * 07-concept-cross-linking.md`).
 *
 * The original design spec (`docs/design/quran-graphrag.html`) envisioned a real knowledge
 * graph: LLM triple-extraction over tafsir text, entity linking, a scholar-reviewed predicate
 * schema. None of that exists yet, and building it means introducing an LLM into an ingest
 * pipeline that has been deliberately zero-LLM and deterministic from day one — a real
 * architectural decision, not a triage call.
 *
 * What DOES already exist: `src/review/problem-verses.ts` — 55 verses, hand-curated, each
 * tagged with one of 12 emotional themes. This script surfaces exactly that, and nothing more,
 * as a browsable index — a cheap, honest way to test whether readers want concept-style
 * navigation at all before any bigger investment.
 *
 * Depends on NOTHING in data/ — `problem-verses.ts` is a plain, self-contained TS module, so
 * this runs even in a worktree that has never run `bun run ingest`.
 *
 *   bun run app:themes
 */
import { PROBLEM_VERSES, THEME_LABELS, type Theme } from "../review/problem-verses.ts";

const OUT_TS = "web/src/theme-index.ts";

// Preserve the order themes first appear in problem-verses.ts — that ordering is itself
// curated (most-reached-for first), not alphabetical, and there is no reason to discard it.
const order: Theme[] = [];
for (const v of PROBLEM_VERSES) {
  if (!order.includes(v.theme)) order.push(v.theme);
}

// `theme` in the generated index is the READER-FACING label (Indonesian). The English `Theme` key
// stays internal to retrieval scoring (web/src/retrieve.ts) and never ships to the browse UI.
const grouped = order.map((theme) => ({
  theme: THEME_LABELS[theme],
  verses: PROBLEM_VERSES.filter((v) => v.theme === theme).map((v) => ({
    surah: v.ref[0],
    ayah: v.ref[1],
    ref: `${v.ref[0]}:${v.ref[1]}`,
    why: v.why,
  })),
}));

const total = grouped.reduce((n, g) => n + g.verses.length, 0);
if (total !== PROBLEM_VERSES.length) {
  throw new Error(`grouped ${total} verses, expected ${PROBLEM_VERSES.length} — a verse was dropped or duplicated`);
}

const ts = `// GENERATED by \`bun run app:themes\` — do not edit. Source: src/review/problem-verses.ts.
//
// Path A from issue 07: the cheap, honest version of "concept navigation" — surfaces the
// EXISTING 12-theme lexicon (already used to score chat retrieval) as a browsable index, rather
// than committing to the full LLM-extracted knowledge graph the original spec envisioned. Only
// covers the 55 hand-curated verses today; each verse's actual text is fetched from the existing
// per-surah shard (web/public/surah/{n}.json), not duplicated here.

export interface ThemeVerse {
  readonly surah: number;
  readonly ayah: number;
  readonly ref: string;
  readonly why: string;
}

export interface ThemeGroup {
  readonly theme: string;
  readonly verses: readonly ThemeVerse[];
}

export const THEME_INDEX: readonly ThemeGroup[] = ${JSON.stringify(grouped, null, 2)} as const;
`;

await Bun.write(OUT_TS, ts);
console.log(`✓ themes   ${grouped.length} themes, ${total} verses → ${OUT_TS} (${(Buffer.byteLength(ts) / 1024).toFixed(1)} KB, inlined)`);
