#!/usr/bin/env bun
/**
 * "Related verses" — the smallest honest slice of issue 07's original cross-linking ask,
 * built from the Path B2 pilot's THEMATICALLY_LINKED_TO edges (`data/review/graph-extraction.json`).
 *
 * Deliberately narrow, for two reasons:
 *
 * 1. **Cross-surah only.** 22 of the pilot's 26 THEMATICALLY_LINKED_TO edges connect ADJACENT
 *    verses within the same tafsir passage (e.g. 39:53 → 39:54..59) — a reader already sees
 *    those together in continuous reading, so surfacing them as a special "link" adds noise, not
 *    navigation. The 4 that cross a surah boundary are the genuine differentiator (e.g. Al-Baqarah
 *    2:153 → Al-Hadid 57:4, both carrying the exact phrase "He is with you wherever you are") —
 *    real concept-to-concept navigation the reading surface can't give you on its own.
 * 2. **Every edge hand-verified**, not just confidence-filtered. All 4 were read against their
 *    evidence_span before this script existed — see `.scratch/nur-phase2-trust-and-depth/issues/
 *    09b-knowledge-graph-b2-derived.md`. At this volume that's cheap; it stops being cheap well
 *    before it stops being necessary, which is exactly why T1/doctrinal predicates stay
 *    unreviewed until real scholar capacity exists (same file).
 *
 * Per the spec's own tiering (`docs/design/quran-graphrag.html` § Stage 06), THEMATICALLY_LINKED_TO
 * is T2 — auto, ranking/navigation only, never a doctrinal citation. This script does not change
 * that: it surfaces the edge as a "related verse" pointer, never as an assertion in Nur's voice.
 *
 * Graceful no-op if `data/review/graph-extraction.json` doesn't exist — same property
 * `build-themes.ts` has relative to `data/`: a worktree that never ran the Path B2 pilot still
 * builds cleanly, just without this (small, optional) enrichment.
 *
 *   bun run app:related
 */
export {}; // no imports otherwise — this makes top-level await legal

const OUT_TS = "web/src/related-verses.ts";
const EXTRACTION_PATH = "data/review/graph-extraction.json";
const SURAHS_PATH = "data/canonical/surahs.json";
const SOURCES_PATH = "data/canonical/tafsir-sources.json";

interface ExtractedEdge {
  predicate: string;
  subject_id: string;
  object: string | { type: string; label: string };
  source_id: string;
  review_status: string;
}
interface Surah {
  number: number;
  name_translit: string;
}
interface TafsirSource {
  id: string;
  author: string;
}

interface RelatedVerse {
  readonly ref: string;
  readonly surah_name: string;
  readonly source: string;
}

const parseAyahId = (id: string): { surah: number; ayah: number } | null => {
  const m = /^ayah:(\d+):(\d+)$/.exec(id);
  return m ? { surah: Number(m[1]), ayah: Number(m[2]) } : null;
};

async function main(): Promise<void> {
  const header = `// GENERATED by \`bun run app:related\` — do not edit. Source: data/review/graph-extraction.json.
//
// The smallest honest slice of issue 07's cross-linking ask: only the 4 hand-verified,
// cross-surah THEMATICALLY_LINKED_TO edges from the Path B2 pilot (T2 — auto, navigation only,
// never a doctrinal citation). See src/app/build-related-verses.ts for why this is narrow on
// purpose, and .scratch/nur-phase2-trust-and-depth/issues/09b-knowledge-graph-b2-derived.md for
// the review record.

export interface RelatedVerse {
  readonly ref: string;
  readonly surah_name: string;
  readonly source: string;
}

`;

  const extractionFile = Bun.file(EXTRACTION_PATH);
  if (!(await extractionFile.exists())) {
    await Bun.write(OUT_TS, `${header}export const RELATED_VERSES: Readonly<Record<string, readonly RelatedVerse[]>> = {};\n`);
    console.log(`✓ related  no ${EXTRACTION_PATH} found — wrote an empty index (run the Path B2 pilot to populate)`);
    return;
  }

  const edges = (await extractionFile.json()) as ExtractedEdge[];
  const surahs = (await Bun.file(SURAHS_PATH).json()) as Surah[];
  const sources = (await Bun.file(SOURCES_PATH).json()) as TafsirSource[];

  const surahName = new Map(surahs.map((s) => [s.number, s.name_translit]));
  const sourceAuthor = new Map(sources.map((s) => [s.id, s.author]));

  const grouped = new Map<string, RelatedVerse[]>();

  for (const e of edges) {
    if (e.predicate !== "THEMATICALLY_LINKED_TO") continue;
    if (e.review_status === "rejected") continue;
    if (typeof e.object !== "string") continue; // THEMATICALLY_LINKED_TO's object is always an ayah id

    const from = parseAyahId(e.subject_id);
    const to = parseAyahId(e.object);
    if (!from || !to) continue;
    if (from.surah === to.surah) continue; // same-surah adjacency — see file header

    const fromRef = `${from.surah}:${from.ayah}`;
    const toRef = `${to.surah}:${to.ayah}`;
    const name = surahName.get(to.surah);
    const author = sourceAuthor.get(e.source_id);
    if (!name || !author) {
      throw new Error(`related-verses: unresolved surah or source for edge ${fromRef} -> ${toRef} (${e.source_id})`);
    }

    const list = grouped.get(fromRef) ?? [];
    list.push({ ref: toRef, surah_name: name, source: `Tafsir ${author}` });
    grouped.set(fromRef, list);
  }

  const obj = Object.fromEntries(grouped);
  const count = [...grouped.values()].reduce((n, l) => n + l.length, 0);

  await Bun.write(OUT_TS, `${header}export const RELATED_VERSES: Readonly<Record<string, readonly RelatedVerse[]>> = ${JSON.stringify(obj, null, 2)} as const;\n`);
  console.log(`✓ related  ${count} cross-surah links, ${grouped.size} source verses → ${OUT_TS}`);
}

await main();
