/**
 * Indonesian renderings of the 154 kitab (book) titles in Ṣaḥīḥ al-Bukhārī and Ṣaḥīḥ Muslim.
 *
 * WHAT THIS IS, AND WHAT IT IS NOT
 * --------------------------------
 * These are STRUCTURAL LABELS — the names of the volumes a reader navigates through — not hadith
 * text and not commentary. "كتاب الإيمان" is "Kitab Iman" in the same way a shelf marked
 * "Astronomy" is "Astronomi": rendering it carries no interpretive claim about anything on the
 * shelf. That distinction is why this file can exist while the hadith TEXT stays Arabic-only.
 *
 * The nomenclature is settled — these titles appear in the same form across every published
 * Indonesian edition of the Ṣaḥīḥayn — so they are authored here rather than machine-generated.
 * Where a term has no ordinary Indonesian equivalent the transliteration leads and the gloss
 * follows in parentheses (`Syufah (Hak Prioritas)`), so a reader learns the term instead of being
 * handed a paraphrase that quietly replaces it.
 *
 * Missing entries render nothing. A title with no mapping shows Arabic alone, exactly as before —
 * never a placeholder, never a guess.
 *
 * Erik, 2026-08-10: the cards were Arabic-only and unreadable to a non-Arabic reader.
 */

/** `${collection}:${bookNo}` → Indonesian title. */
export const KITAB_ID: Readonly<Record<string, string>> = {
  "bukhari:1": "Permulaan Wahyu",
  "bukhari:2": "Iman",
  "bukhari:3": "Ilmu",
  "bukhari:4": "Wudu",
  "bukhari:5": "Mandi Junub",
  "bukhari:6": "Haid",
  "bukhari:7": "Tayamum",
  "bukhari:8": "Salat",
  "bukhari:9": "Waktu-waktu Salat",
  "bukhari:10": "Azan",
  "bukhari:11": "Salat Jumat",
  "bukhari:12": "Salat Khauf",
  "bukhari:13": "Dua Hari Raya",
  "bukhari:14": "Salat Witir",
  "bukhari:15": "Salat Istisqa (Minta Hujan)",
  "bukhari:16": "Salat Gerhana",
  "bukhari:17": "Sujud Tilawah",
  "bukhari:18": "Mengqasar Salat",
  "bukhari:19": "Salat Tahajud",
  "bukhari:20": "Keutamaan Salat di Masjid Makkah dan Madinah",
  "bukhari:21": "Perbuatan dalam Salat",
  "bukhari:22": "Sujud Sahwi",
  "bukhari:23": "Jenazah",
  "bukhari:24": "Zakat",
  "bukhari:25": "Haji",
  "bukhari:26": "Umrah",
  "bukhari:27": "Terhalang Ihram (Ihsar)",
  "bukhari:28": "Denda Berburu",
  "bukhari:29": "Keutamaan Madinah",
  "bukhari:30": "Puasa",
  "bukhari:31": "Salat Tarawih",
  "bukhari:32": "Keutamaan Lailatulqadar",
  "bukhari:33": "Iktikaf",
  "bukhari:34": "Jual Beli",
  "bukhari:35": "Jual Beli Salam",
  "bukhari:36": "Syufah (Hak Prioritas)",
  "bukhari:37": "Sewa-menyewa",
  "bukhari:38": "Pengalihan Utang (Hawalah)",
  "bukhari:39": "Penjaminan (Kafalah)",
  "bukhari:40": "Perwakilan (Wakalah)",
  "bukhari:41": "Bagi Hasil Pertanian",
  "bukhari:42": "Pengairan Kebun (Musaqah)",
  "bukhari:43": "Pinjam-meminjam",
  "bukhari:44": "Persengketaan",
  "bukhari:45": "Barang Temuan",
  "bukhari:46": "Kezaliman",
  "bukhari:47": "Perserikatan (Syirkah)",
  "bukhari:48": "Gadai",
  "bukhari:49": "Memerdekakan Budak",
  "bukhari:50": "Budak Mukatab",
  "bukhari:51": "Hibah dan Keutamaannya",
  "bukhari:52": "Persaksian",
  "bukhari:53": "Perdamaian",
  "bukhari:54": "Syarat-syarat",
  "bukhari:55": "Wasiat",
  "bukhari:56": "Jihad dan Peperangan",
  "bukhari:57": "Pembagian Seperlima Rampasan",
  "bukhari:58": "Jizyah dan Perjanjian Damai",
  "bukhari:59": "Permulaan Penciptaan",
  "bukhari:60": "Kisah Para Nabi",
  "bukhari:61": "Keutamaan (Manaqib)",
  "bukhari:62": "Keutamaan Sahabat Nabi",
  "bukhari:63": "Keutamaan Kaum Ansar",
  "bukhari:64": "Peperangan Nabi (Magazi)",
  "bukhari:65": "Tafsir",
  "bukhari:66": "Keutamaan Al-Qur'an",
  "bukhari:67": "Nikah",
  "bukhari:68": "Talak",
  "bukhari:69": "Nafkah",
  "bukhari:70": "Makanan",
  "bukhari:71": "Akikah",
  "bukhari:72": "Sembelihan dan Buruan",
  "bukhari:73": "Kurban",
  "bukhari:74": "Minuman",
  "bukhari:75": "Orang Sakit",
  "bukhari:76": "Pengobatan",
  "bukhari:77": "Pakaian",
  "bukhari:78": "Adab",
  "bukhari:79": "Meminta Izin",
  "bukhari:80": "Doa",
  "bukhari:81": "Pelembut Hati",
  "bukhari:82": "Takdir",
  "bukhari:83": "Sumpah dan Nazar",
  "bukhari:84": "Kafarat Sumpah",
  "bukhari:85": "Warisan",
  "bukhari:86": "Hudud",
  "bukhari:87": "Diat",
  "bukhari:88": "Taubat Orang Murtad dan Memeranginya",
  "bukhari:89": "Paksaan",
  "bukhari:90": "Tipu Muslihat (Hilah)",
  "bukhari:91": "Tafsir Mimpi",
  "bukhari:92": "Fitnah",
  "bukhari:93": "Hukum-hukum",
  "bukhari:94": "Angan-angan",
  "bukhari:95": "Khabar Ahad",
  "bukhari:96": "Berpegang pada Kitab dan Sunah",
  "bukhari:97": "Tauhid",

  "muslim:0": "Mukadimah",
  "muslim:1": "Iman",
  "muslim:2": "Bersuci",
  "muslim:3": "Haid",
  "muslim:4": "Salat",
  "muslim:5": "Masjid dan Tempat Salat",
  "muslim:6": "Salat Musafir dan Qasarnya",
  "muslim:7": "Salat Jumat",
  "muslim:8": "Salat Dua Hari Raya",
  "muslim:9": "Salat Istisqa",
  "muslim:10": "Salat Gerhana",
  "muslim:11": "Jenazah",
  "muslim:12": "Zakat",
  "muslim:13": "Puasa",
  "muslim:14": "Iktikaf",
  "muslim:15": "Haji",
  "muslim:16": "Nikah",
  "muslim:17": "Persusuan",
  "muslim:18": "Talak",
  "muslim:19": "Lian",
  "muslim:20": "Memerdekakan Budak",
  "muslim:21": "Jual Beli",
  "muslim:22": "Musaqah",
  "muslim:23": "Warisan",
  "muslim:24": "Hibah",
  "muslim:25": "Wasiat",
  "muslim:26": "Nazar",
  "muslim:27": "Sumpah",
  "muslim:28": "Qasamah, Hirabah, Kisas dan Diat",
  "muslim:29": "Hudud",
  "muslim:30": "Peradilan",
  "muslim:31": "Barang Temuan",
  "muslim:32": "Jihad dan Peperangan",
  "muslim:33": "Kepemimpinan",
  "muslim:34": "Buruan, Sembelihan dan Hewan yang Halal",
  "muslim:35": "Kurban",
  "muslim:36": "Minuman",
  "muslim:37": "Pakaian dan Perhiasan",
  "muslim:38": "Adab",
  "muslim:39": "Salam",
  "muslim:40": "Ungkapan dalam Adab dan Lainnya",
  "muslim:41": "Syair",
  "muslim:42": "Mimpi",
  "muslim:43": "Keutamaan",
  "muslim:44": "Keutamaan Para Sahabat",
  "muslim:45": "Kebajikan, Silaturahmi dan Adab",
  "muslim:46": "Takdir",
  "muslim:47": "Ilmu",
  "muslim:48": "Zikir, Doa, Taubat dan Istigfar",
  "muslim:49": "Pelembut Hati",
  "muslim:50": "Taubat",
  "muslim:51": "Sifat Orang Munafik dan Hukumnya",
  "muslim:52": "Sifat Kiamat, Surga dan Neraka",
  "muslim:53": "Surga, Kenikmatan dan Penghuninya",
  "muslim:54": "Fitnah dan Tanda-tanda Kiamat",
  "muslim:55": "Zuhud dan Pelembut Hati",
  "muslim:56": "Tafsir",
};

/** The Indonesian title for a kitab, or null when we have none. Never guesses. */
export function kitabId(collection: string, no: number): string | null {
  return KITAB_ID[`${collection}:${no}`] ?? null;
}
