// GENERATED by `bun run app:juz` — do not edit.
//
// The 30 juz boundaries, from Tanzil's quran-data.xml (sha256-pinned). Inlined rather than
// fetched so "which juz is this ayah in" needs no network. Only starts and ends are stored;
// per-ayah juz numbers are derived in juz.ts so the two can never disagree.

export interface JuzSpan {
  /** Juz number, 1-30. */
  readonly n: number;
  /** First ayah of the juz. */
  readonly s: number;
  readonly a: number;
  /** Last ayah of the juz. */
  readonly es: number;
  readonly ea: number;
  readonly ayahs: number;
  readonly from: string;
  readonly to: string;
}

export const JUZ: readonly JuzSpan[] = [
  { n: 1, s: 1, a: 1, es: 2, ea: 141, ayahs: 148, from: "Al-Faatiha", to: "Al-Baqara" },
  { n: 2, s: 2, a: 142, es: 2, ea: 252, ayahs: 111, from: "Al-Baqara", to: "Al-Baqara" },
  { n: 3, s: 2, a: 253, es: 3, ea: 92, ayahs: 126, from: "Al-Baqara", to: "Aal-i-Imraan" },
  { n: 4, s: 3, a: 93, es: 4, ea: 23, ayahs: 131, from: "Aal-i-Imraan", to: "An-Nisaa" },
  { n: 5, s: 4, a: 24, es: 4, ea: 147, ayahs: 124, from: "An-Nisaa", to: "An-Nisaa" },
  { n: 6, s: 4, a: 148, es: 5, ea: 81, ayahs: 110, from: "An-Nisaa", to: "Al-Maaida" },
  { n: 7, s: 5, a: 82, es: 6, ea: 110, ayahs: 149, from: "Al-Maaida", to: "Al-An'aam" },
  { n: 8, s: 6, a: 111, es: 7, ea: 87, ayahs: 142, from: "Al-An'aam", to: "Al-A'raaf" },
  { n: 9, s: 7, a: 88, es: 8, ea: 40, ayahs: 159, from: "Al-A'raaf", to: "Al-Anfaal" },
  { n: 10, s: 8, a: 41, es: 9, ea: 92, ayahs: 127, from: "Al-Anfaal", to: "At-Tawba" },
  { n: 11, s: 9, a: 93, es: 11, ea: 5, ayahs: 151, from: "At-Tawba", to: "Hud" },
  { n: 12, s: 11, a: 6, es: 12, ea: 52, ayahs: 170, from: "Hud", to: "Yusuf" },
  { n: 13, s: 12, a: 53, es: 14, ea: 52, ayahs: 154, from: "Yusuf", to: "Ibrahim" },
  { n: 14, s: 15, a: 1, es: 16, ea: 128, ayahs: 227, from: "Al-Hijr", to: "An-Nahl" },
  { n: 15, s: 17, a: 1, es: 18, ea: 74, ayahs: 185, from: "Al-Israa", to: "Al-Kahf" },
  { n: 16, s: 18, a: 75, es: 20, ea: 135, ayahs: 269, from: "Al-Kahf", to: "Taa-Haa" },
  { n: 17, s: 21, a: 1, es: 22, ea: 78, ayahs: 190, from: "Al-Anbiyaa", to: "Al-Hajj" },
  { n: 18, s: 23, a: 1, es: 25, ea: 20, ayahs: 202, from: "Al-Muminoon", to: "Al-Furqaan" },
  { n: 19, s: 25, a: 21, es: 27, ea: 55, ayahs: 339, from: "Al-Furqaan", to: "An-Naml" },
  { n: 20, s: 27, a: 56, es: 29, ea: 45, ayahs: 171, from: "An-Naml", to: "Al-Ankaboot" },
  { n: 21, s: 29, a: 46, es: 33, ea: 30, ayahs: 178, from: "Al-Ankaboot", to: "Al-Ahzaab" },
  { n: 22, s: 33, a: 31, es: 36, ea: 27, ayahs: 169, from: "Al-Ahzaab", to: "Yaseen" },
  { n: 23, s: 36, a: 28, es: 39, ea: 31, ayahs: 357, from: "Yaseen", to: "Az-Zumar" },
  { n: 24, s: 39, a: 32, es: 41, ea: 46, ayahs: 175, from: "Az-Zumar", to: "Fussilat" },
  { n: 25, s: 41, a: 47, es: 45, ea: 37, ayahs: 246, from: "Fussilat", to: "Al-Jaathiya" },
  { n: 26, s: 46, a: 1, es: 51, ea: 30, ayahs: 195, from: "Al-Ahqaf", to: "Adh-Dhaariyat" },
  { n: 27, s: 51, a: 31, es: 57, ea: 29, ayahs: 399, from: "Adh-Dhaariyat", to: "Al-Hadid" },
  { n: 28, s: 58, a: 1, es: 66, ea: 12, ayahs: 137, from: "Al-Mujaadila", to: "At-Tahrim" },
  { n: 29, s: 67, a: 1, es: 77, ea: 50, ayahs: 431, from: "Al-Mulk", to: "Al-Mursalaat" },
  { n: 30, s: 78, a: 1, es: 114, ea: 6, ayahs: 564, from: "An-Naba", to: "An-Naas" },
];
