// GENERATED by `bun run app:related` — do not edit. Source: data/review/graph-extraction.json.
//
// The smallest honest slice of issue 07's cross-linking ask: only the 4 hand-verified,
// cross-surah THEMATICALLY_LINKED_TO edges from the Path B2 pilot (T2 — auto, navigation only,
// never a doctrinal citation). See src/app/build-related-verses.ts for why this is narrow on
// purpose, and .scratch/nur-phase2-trust-and-depth/issues/09b-knowledge-graph-b2-derived.md for
// the review record.

export interface RelatedVerse {
  readonly ref: string;
  readonly surah_name: string;
  readonly source: string;
}

export const RELATED_VERSES: Readonly<Record<string, readonly RelatedVerse[]>> = {
  "2:153": [
    {
      "ref": "57:4",
      "surah_name": "Al-Hadid",
      "source": "Tafsir Abd ar-Rahman as-Sa'di"
    }
  ],
  "2:186": [
    {
      "ref": "8:29",
      "surah_name": "Al-Anfaal",
      "source": "Tafsir Abd ar-Rahman as-Sa'di"
    }
  ],
  "2:154": [
    {
      "ref": "33:44",
      "surah_name": "Al-Ahzaab",
      "source": "Tafsir Ismail ibn Kathir"
    }
  ],
  "2:214": [
    {
      "ref": "33:11",
      "surah_name": "Al-Ahzaab",
      "source": "Tafsir Ismail ibn Kathir"
    }
  ]
} as const;
