// GENERATED by `bun run app:corpus` — do not edit.
//
// The truth oracle. Inlined into the bundle (not fetched) so Nur can prove an ayah is real
// with ZERO network — offline, on a dead connection, on the very first cold open. This is the
// cheapest possible form of "never lie about what the Qur'an contains", and it is why the app
// can no longer tell a user that 18:10 does not exist.

export interface SurahMeta {
  /** Surah number, 1-114. */
  readonly n: number;
  readonly ar: string;
  readonly tl: string;
  readonly en: string;
  /** How many ayahs this surah actually has — the bound every reference is checked against. */
  readonly ayahs: number;
  readonly rev: string;
  /** Does this surah open with an unnumbered basmalah? (false for Al-Faatiha and At-Tawbah) */
  readonly bismillah: boolean;
}

export const SURAH_INDEX: readonly SurahMeta[] = [
  {
    "n": 1,
    "ar": "الفاتحة",
    "tl": "Al-Faatiha",
    "en": "The Opening",
    "ayahs": 7,
    "rev": "meccan",
    "bismillah": false
  },
  {
    "n": 2,
    "ar": "البقرة",
    "tl": "Al-Baqara",
    "en": "The Cow",
    "ayahs": 286,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 3,
    "ar": "آل عمران",
    "tl": "Aal-i-Imraan",
    "en": "The Family of Imraan",
    "ayahs": 200,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 4,
    "ar": "النساء",
    "tl": "An-Nisaa",
    "en": "The Women",
    "ayahs": 176,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 5,
    "ar": "المائدة",
    "tl": "Al-Maaida",
    "en": "The Table",
    "ayahs": 120,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 6,
    "ar": "الأنعام",
    "tl": "Al-An'aam",
    "en": "The Cattle",
    "ayahs": 165,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 7,
    "ar": "الأعراف",
    "tl": "Al-A'raaf",
    "en": "The Heights",
    "ayahs": 206,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 8,
    "ar": "الأنفال",
    "tl": "Al-Anfaal",
    "en": "The Spoils of War",
    "ayahs": 75,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 9,
    "ar": "التوبة",
    "tl": "At-Tawba",
    "en": "The Repentance",
    "ayahs": 129,
    "rev": "medinan",
    "bismillah": false
  },
  {
    "n": 10,
    "ar": "يونس",
    "tl": "Yunus",
    "en": "Jonas",
    "ayahs": 109,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 11,
    "ar": "هود",
    "tl": "Hud",
    "en": "Hud",
    "ayahs": 123,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 12,
    "ar": "يوسف",
    "tl": "Yusuf",
    "en": "Joseph",
    "ayahs": 111,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 13,
    "ar": "الرعد",
    "tl": "Ar-Ra'd",
    "en": "The Thunder",
    "ayahs": 43,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 14,
    "ar": "ابراهيم",
    "tl": "Ibrahim",
    "en": "Abraham",
    "ayahs": 52,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 15,
    "ar": "الحجر",
    "tl": "Al-Hijr",
    "en": "The Rock",
    "ayahs": 99,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 16,
    "ar": "النحل",
    "tl": "An-Nahl",
    "en": "The Bee",
    "ayahs": 128,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 17,
    "ar": "الإسراء",
    "tl": "Al-Israa",
    "en": "The Night Journey",
    "ayahs": 111,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 18,
    "ar": "الكهف",
    "tl": "Al-Kahf",
    "en": "The Cave",
    "ayahs": 110,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 19,
    "ar": "مريم",
    "tl": "Maryam",
    "en": "Mary",
    "ayahs": 98,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 20,
    "ar": "طه",
    "tl": "Taa-Haa",
    "en": "Taa-Haa",
    "ayahs": 135,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 21,
    "ar": "الأنبياء",
    "tl": "Al-Anbiyaa",
    "en": "The Prophets",
    "ayahs": 112,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 22,
    "ar": "الحج",
    "tl": "Al-Hajj",
    "en": "The Pilgrimage",
    "ayahs": 78,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 23,
    "ar": "المؤمنون",
    "tl": "Al-Muminoon",
    "en": "The Believers",
    "ayahs": 118,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 24,
    "ar": "النور",
    "tl": "An-Noor",
    "en": "The Light",
    "ayahs": 64,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 25,
    "ar": "الفرقان",
    "tl": "Al-Furqaan",
    "en": "The Criterion",
    "ayahs": 77,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 26,
    "ar": "الشعراء",
    "tl": "Ash-Shu'araa",
    "en": "The Poets",
    "ayahs": 227,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 27,
    "ar": "النمل",
    "tl": "An-Naml",
    "en": "The Ant",
    "ayahs": 93,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 28,
    "ar": "القصص",
    "tl": "Al-Qasas",
    "en": "The Stories",
    "ayahs": 88,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 29,
    "ar": "العنكبوت",
    "tl": "Al-Ankaboot",
    "en": "The Spider",
    "ayahs": 69,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 30,
    "ar": "الروم",
    "tl": "Ar-Room",
    "en": "The Romans",
    "ayahs": 60,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 31,
    "ar": "لقمان",
    "tl": "Luqman",
    "en": "Luqman",
    "ayahs": 34,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 32,
    "ar": "السجدة",
    "tl": "As-Sajda",
    "en": "The Prostration",
    "ayahs": 30,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 33,
    "ar": "الأحزاب",
    "tl": "Al-Ahzaab",
    "en": "The Clans",
    "ayahs": 73,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 34,
    "ar": "سبإ",
    "tl": "Saba",
    "en": "Sheba",
    "ayahs": 54,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 35,
    "ar": "فاطر",
    "tl": "Faatir",
    "en": "The Originator",
    "ayahs": 45,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 36,
    "ar": "يس",
    "tl": "Yaseen",
    "en": "Yaseen",
    "ayahs": 83,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 37,
    "ar": "الصافات",
    "tl": "As-Saaffaat",
    "en": "Those drawn up in Ranks",
    "ayahs": 182,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 38,
    "ar": "ص",
    "tl": "Saad",
    "en": "The letter Saad",
    "ayahs": 88,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 39,
    "ar": "الزمر",
    "tl": "Az-Zumar",
    "en": "The Groups",
    "ayahs": 75,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 40,
    "ar": "غافر",
    "tl": "Al-Ghaafir",
    "en": "The Forgiver",
    "ayahs": 85,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 41,
    "ar": "فصلت",
    "tl": "Fussilat",
    "en": "Explained in detail",
    "ayahs": 54,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 42,
    "ar": "الشورى",
    "tl": "Ash-Shura",
    "en": "Consultation",
    "ayahs": 53,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 43,
    "ar": "الزخرف",
    "tl": "Az-Zukhruf",
    "en": "Ornaments of gold",
    "ayahs": 89,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 44,
    "ar": "الدخان",
    "tl": "Ad-Dukhaan",
    "en": "The Smoke",
    "ayahs": 59,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 45,
    "ar": "الجاثية",
    "tl": "Al-Jaathiya",
    "en": "Crouching",
    "ayahs": 37,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 46,
    "ar": "الأحقاف",
    "tl": "Al-Ahqaf",
    "en": "The Dunes",
    "ayahs": 35,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 47,
    "ar": "محمد",
    "tl": "Muhammad",
    "en": "Muhammad",
    "ayahs": 38,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 48,
    "ar": "الفتح",
    "tl": "Al-Fath",
    "en": "The Victory",
    "ayahs": 29,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 49,
    "ar": "الحجرات",
    "tl": "Al-Hujuraat",
    "en": "The Inner Apartments",
    "ayahs": 18,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 50,
    "ar": "ق",
    "tl": "Qaaf",
    "en": "The letter Qaaf",
    "ayahs": 45,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 51,
    "ar": "الذاريات",
    "tl": "Adh-Dhaariyat",
    "en": "The Winnowing Winds",
    "ayahs": 60,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 52,
    "ar": "الطور",
    "tl": "At-Tur",
    "en": "The Mount",
    "ayahs": 49,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 53,
    "ar": "النجم",
    "tl": "An-Najm",
    "en": "The Star",
    "ayahs": 62,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 54,
    "ar": "القمر",
    "tl": "Al-Qamar",
    "en": "The Moon",
    "ayahs": 55,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 55,
    "ar": "الرحمن",
    "tl": "Ar-Rahmaan",
    "en": "The Beneficent",
    "ayahs": 78,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 56,
    "ar": "الواقعة",
    "tl": "Al-Waaqia",
    "en": "The Inevitable",
    "ayahs": 96,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 57,
    "ar": "الحديد",
    "tl": "Al-Hadid",
    "en": "The Iron",
    "ayahs": 29,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 58,
    "ar": "المجادلة",
    "tl": "Al-Mujaadila",
    "en": "The Pleading Woman",
    "ayahs": 22,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 59,
    "ar": "الحشر",
    "tl": "Al-Hashr",
    "en": "The Exile",
    "ayahs": 24,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 60,
    "ar": "الممتحنة",
    "tl": "Al-Mumtahana",
    "en": "She that is to be examined",
    "ayahs": 13,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 61,
    "ar": "الصف",
    "tl": "As-Saff",
    "en": "The Ranks",
    "ayahs": 14,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 62,
    "ar": "الجمعة",
    "tl": "Al-Jumu'a",
    "en": "Friday",
    "ayahs": 11,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 63,
    "ar": "المنافقون",
    "tl": "Al-Munaafiqoon",
    "en": "The Hypocrites",
    "ayahs": 11,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 64,
    "ar": "التغابن",
    "tl": "At-Taghaabun",
    "en": "Mutual Disillusion",
    "ayahs": 18,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 65,
    "ar": "الطلاق",
    "tl": "At-Talaaq",
    "en": "Divorce",
    "ayahs": 12,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 66,
    "ar": "التحريم",
    "tl": "At-Tahrim",
    "en": "The Prohibition",
    "ayahs": 12,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 67,
    "ar": "الملك",
    "tl": "Al-Mulk",
    "en": "The Sovereignty",
    "ayahs": 30,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 68,
    "ar": "القلم",
    "tl": "Al-Qalam",
    "en": "The Pen",
    "ayahs": 52,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 69,
    "ar": "الحاقة",
    "tl": "Al-Haaqqa",
    "en": "The Reality",
    "ayahs": 52,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 70,
    "ar": "المعارج",
    "tl": "Al-Ma'aarij",
    "en": "The Ascending Stairways",
    "ayahs": 44,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 71,
    "ar": "نوح",
    "tl": "Nooh",
    "en": "Noah",
    "ayahs": 28,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 72,
    "ar": "الجن",
    "tl": "Al-Jinn",
    "en": "The Jinn",
    "ayahs": 28,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 73,
    "ar": "المزمل",
    "tl": "Al-Muzzammil",
    "en": "The Enshrouded One",
    "ayahs": 20,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 74,
    "ar": "المدثر",
    "tl": "Al-Muddaththir",
    "en": "The Cloaked One",
    "ayahs": 56,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 75,
    "ar": "القيامة",
    "tl": "Al-Qiyaama",
    "en": "The Resurrection",
    "ayahs": 40,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 76,
    "ar": "الانسان",
    "tl": "Al-Insaan",
    "en": "Man",
    "ayahs": 31,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 77,
    "ar": "المرسلات",
    "tl": "Al-Mursalaat",
    "en": "The Emissaries",
    "ayahs": 50,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 78,
    "ar": "النبإ",
    "tl": "An-Naba",
    "en": "The Announcement",
    "ayahs": 40,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 79,
    "ar": "النازعات",
    "tl": "An-Naazi'aat",
    "en": "Those who drag forth",
    "ayahs": 46,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 80,
    "ar": "عبس",
    "tl": "Abasa",
    "en": "He frowned",
    "ayahs": 42,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 81,
    "ar": "التكوير",
    "tl": "At-Takwir",
    "en": "The Overthrowing",
    "ayahs": 29,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 82,
    "ar": "الإنفطار",
    "tl": "Al-Infitaar",
    "en": "The Cleaving",
    "ayahs": 19,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 83,
    "ar": "المطففين",
    "tl": "Al-Mutaffifin",
    "en": "Defrauding",
    "ayahs": 36,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 84,
    "ar": "الإنشقاق",
    "tl": "Al-Inshiqaaq",
    "en": "The Splitting Open",
    "ayahs": 25,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 85,
    "ar": "البروج",
    "tl": "Al-Burooj",
    "en": "The Constellations",
    "ayahs": 22,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 86,
    "ar": "الطارق",
    "tl": "At-Taariq",
    "en": "The Morning Star",
    "ayahs": 17,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 87,
    "ar": "الأعلى",
    "tl": "Al-A'laa",
    "en": "The Most High",
    "ayahs": 19,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 88,
    "ar": "الغاشية",
    "tl": "Al-Ghaashiya",
    "en": "The Overwhelming",
    "ayahs": 26,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 89,
    "ar": "الفجر",
    "tl": "Al-Fajr",
    "en": "The Dawn",
    "ayahs": 30,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 90,
    "ar": "البلد",
    "tl": "Al-Balad",
    "en": "The City",
    "ayahs": 20,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 91,
    "ar": "الشمس",
    "tl": "Ash-Shams",
    "en": "The Sun",
    "ayahs": 15,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 92,
    "ar": "الليل",
    "tl": "Al-Lail",
    "en": "The Night",
    "ayahs": 21,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 93,
    "ar": "الضحى",
    "tl": "Ad-Dhuhaa",
    "en": "The Morning Hours",
    "ayahs": 11,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 94,
    "ar": "الشرح",
    "tl": "Ash-Sharh",
    "en": "The Consolation",
    "ayahs": 8,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 95,
    "ar": "التين",
    "tl": "At-Tin",
    "en": "The Fig",
    "ayahs": 8,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 96,
    "ar": "العلق",
    "tl": "Al-Alaq",
    "en": "The Clot",
    "ayahs": 19,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 97,
    "ar": "القدر",
    "tl": "Al-Qadr",
    "en": "The Power, Fate",
    "ayahs": 5,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 98,
    "ar": "البينة",
    "tl": "Al-Bayyina",
    "en": "The Evidence",
    "ayahs": 8,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 99,
    "ar": "الزلزلة",
    "tl": "Az-Zalzala",
    "en": "The Earthquake",
    "ayahs": 8,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 100,
    "ar": "العاديات",
    "tl": "Al-Aadiyaat",
    "en": "The Chargers",
    "ayahs": 11,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 101,
    "ar": "القارعة",
    "tl": "Al-Qaari'a",
    "en": "The Calamity",
    "ayahs": 11,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 102,
    "ar": "التكاثر",
    "tl": "At-Takaathur",
    "en": "Competition",
    "ayahs": 8,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 103,
    "ar": "العصر",
    "tl": "Al-Asr",
    "en": "The Declining Day, Epoch",
    "ayahs": 3,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 104,
    "ar": "الهمزة",
    "tl": "Al-Humaza",
    "en": "The Traducer",
    "ayahs": 9,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 105,
    "ar": "الفيل",
    "tl": "Al-Fil",
    "en": "The Elephant",
    "ayahs": 5,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 106,
    "ar": "قريش",
    "tl": "Quraish",
    "en": "Quraysh",
    "ayahs": 4,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 107,
    "ar": "الماعون",
    "tl": "Al-Maa'un",
    "en": "Almsgiving",
    "ayahs": 7,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 108,
    "ar": "الكوثر",
    "tl": "Al-Kawthar",
    "en": "Abundance",
    "ayahs": 3,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 109,
    "ar": "الكافرون",
    "tl": "Al-Kaafiroon",
    "en": "The Disbelievers",
    "ayahs": 6,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 110,
    "ar": "النصر",
    "tl": "An-Nasr",
    "en": "Divine Support",
    "ayahs": 3,
    "rev": "medinan",
    "bismillah": true
  },
  {
    "n": 111,
    "ar": "المسد",
    "tl": "Al-Masad",
    "en": "The Palm Fibre",
    "ayahs": 5,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 112,
    "ar": "الإخلاص",
    "tl": "Al-Ikhlaas",
    "en": "Sincerity",
    "ayahs": 4,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 113,
    "ar": "الفلق",
    "tl": "Al-Falaq",
    "en": "The Dawn",
    "ayahs": 5,
    "rev": "meccan",
    "bismillah": true
  },
  {
    "n": 114,
    "ar": "الناس",
    "tl": "An-Naas",
    "en": "Mankind",
    "ayahs": 6,
    "rev": "meccan",
    "bismillah": true
  }
] as const;

/** The basmalah, rendered as an unnumbered opening above every surah but 1 and 9. */
export const BASMALAH = "بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ";

export const TOTAL_AYAHS = 6236;
