// GENERATED by `bun run app:themes` — do not edit. Source: src/review/problem-verses.ts.
//
// Path A from issue 07: the cheap, honest version of "concept navigation" — surfaces the
// EXISTING 12-theme lexicon (already used to score chat retrieval) as a browsable index, rather
// than committing to the full LLM-extracted knowledge graph the original spec envisioned. Only
// covers the 55 hand-curated verses today; each verse's actual text is fetched from the existing
// per-surah shard (web/public/surah/{n}.json), not duplicated here.

export interface ThemeVerse {
  readonly surah: number;
  readonly ayah: number;
  readonly ref: string;
  readonly why: string;
  /** Inclusive ayah range this verse must be shown inside, if the reviewer required one. */
  readonly codisplay?: readonly [number, number];
}

export interface ThemeGroup {
  readonly theme: string;
  readonly verses: readonly ThemeVerse[];
}

export const THEME_INDEX: readonly ThemeGroup[] = [
  {
    "theme": "Kesulitan & kelapangan",
    "verses": [
      {
        "surah": 94,
        "ayah": 5,
        "ref": "94:5",
        "why": "Ayat penghiburan — bersama kesulitan ada kemudahan"
      },
      {
        "surah": 94,
        "ayah": 6,
        "ref": "94:6",
        "why": "Diulang dua kali — itu yang membuatnya janji, bukan kebetulan"
      },
      {
        "surah": 65,
        "ayah": 7,
        "ref": "65:7",
        "why": "Allah akan memberi kemudahan setelah kesulitan"
      },
      {
        "surah": 2,
        "ayah": 286,
        "ref": "2:286",
        "why": "Allah tidak membebani seseorang melebihi kesanggupannya"
      },
      {
        "surah": 65,
        "ayah": 2,
        "ref": "65:2",
        "why": "Jalan keluar bagi orang yang bertakwa"
      },
      {
        "surah": 2,
        "ayah": 214,
        "ref": "2:214",
        "why": "\"Kapan datang pertolongan Allah?\" — jeritan orang yang diuji"
      }
    ]
  },
  {
    "theme": "Cemas & takut",
    "verses": [
      {
        "surah": 13,
        "ayah": 28,
        "ref": "13:28",
        "why": "Hati menjadi tenang dengan mengingat Allah"
      },
      {
        "surah": 3,
        "ayah": 139,
        "ref": "3:139",
        "why": "Jangan lemah, jangan bersedih"
      },
      {
        "surah": 9,
        "ayah": 40,
        "ref": "9:40",
        "why": "\"Jangan sedih — Allah bersama kita\""
      },
      {
        "surah": 20,
        "ayah": 46,
        "ref": "20:46",
        "why": "\"Jangan takut. Aku bersama kalian, mendengar dan melihat\""
      },
      {
        "surah": 41,
        "ayah": 30,
        "ref": "41:30",
        "why": "Para malaikat: \"jangan takut, jangan bersedih\""
      }
    ]
  },
  {
    "theme": "Duka & kehilangan",
    "verses": [
      {
        "surah": 2,
        "ayah": 156,
        "ref": "2:156",
        "why": "Inna lillahi wa inna ilaihi raji'un — dibaca di setiap kematian"
      },
      {
        "surah": 2,
        "ayah": 155,
        "ref": "2:155",
        "why": "\"Kami pasti menguji kalian… sampaikan kabar gembira bagi yang sabar\""
      },
      {
        "surah": 2,
        "ayah": 157,
        "ref": "2:157",
        "why": "Keberkahan dan rahmat bagi mereka yang bertahan"
      },
      {
        "surah": 12,
        "ayah": 86,
        "ref": "12:86",
        "why": "Ya'qub: \"Hanya kepada Allah aku mengadukan kesedihanku\""
      },
      {
        "surah": 3,
        "ayah": 185,
        "ref": "3:185",
        "why": "Setiap yang bernyawa akan merasakan mati"
      },
      {
        "surah": 21,
        "ayah": 35,
        "ref": "21:35",
        "why": "Diuji lewat hal buruk dan hal baik — dua-duanya ujian"
      }
    ]
  },
  {
    "theme": "Kesabaran",
    "verses": [
      {
        "surah": 2,
        "ayah": 153,
        "ref": "2:153",
        "why": "Mintalah pertolongan dengan sabar dan salat"
      },
      {
        "surah": 39,
        "ayah": 10,
        "ref": "39:10",
        "why": "Orang sabar diberi pahala tanpa batas"
      },
      {
        "surah": 3,
        "ayah": 200,
        "ref": "3:200",
        "why": "Sabar, kuatkan kesabaranmu, jangan goyah"
      },
      {
        "surah": 103,
        "ayah": 3,
        "ref": "103:3",
        "why": "Al-'Asr — mereka yang saling menasihati untuk sabar"
      },
      {
        "surah": 8,
        "ayah": 46,
        "ref": "8:46",
        "why": "Allah bersama orang-orang yang sabar"
      }
    ]
  },
  {
    "theme": "Ampunan & putus asa",
    "verses": [
      {
        "surah": 39,
        "ayah": 53,
        "ref": "39:53",
        "why": "\"Jangan berputus asa dari rahmat Allah\" — ayat untuk yang merasa kotor"
      },
      {
        "surah": 3,
        "ayah": 135,
        "ref": "3:135",
        "why": "Siapa yang mengampuni dosa selain Allah?"
      },
      {
        "surah": 66,
        "ayah": 8,
        "ref": "66:8",
        "why": "Kembalilah kepada Allah dengan tobat yang tulus"
      },
      {
        "surah": 24,
        "ayah": 22,
        "ref": "24:22",
        "why": "Maafkan, dan lapangkan dadamu"
      },
      {
        "surah": 4,
        "ayah": 110,
        "ref": "4:110",
        "why": "Siapa pun yang berbuat salah lalu minta ampun"
      },
      {
        "surah": 42,
        "ayah": 25,
        "ref": "42:25",
        "why": "Dia menerima tobat dari hamba-hamba-Nya"
      }
    ]
  },
  {
    "theme": "Rezeki & utang",
    "verses": [
      {
        "surah": 65,
        "ayah": 3,
        "ref": "65:3",
        "why": "Rezeki dari arah yang tidak disangka-sangka"
      },
      {
        "surah": 11,
        "ayah": 6,
        "ref": "11:6",
        "why": "Semua makhluk sudah dijamin rezekinya oleh Allah"
      },
      {
        "surah": 51,
        "ayah": 22,
        "ref": "51:22",
        "why": "Di langit ada rezekimu"
      },
      {
        "surah": 29,
        "ayah": 60,
        "ref": "29:60",
        "why": "Allah yang memberi rezeki kepadanya dan kepadamu"
      },
      {
        "surah": 2,
        "ayah": 280,
        "ref": "2:280",
        "why": "Kalau yang berutang lagi kesulitan, beri dia waktu"
      },
      {
        "surah": 94,
        "ayah": 7,
        "ref": "94:7",
        "why": "Kalau sudah selesai, kerjakan yang berikutnya"
      }
    ]
  },
  {
    "theme": "Tawakal",
    "verses": [
      {
        "surah": 3,
        "ayah": 159,
        "ref": "3:159",
        "why": "Kalau sudah bertekad, bertawakallah kepada Allah"
      },
      {
        "surah": 8,
        "ayah": 2,
        "ref": "8:2",
        "why": "Hatinya bergetar, imannya bertambah, lalu ia bertawakal"
      },
      {
        "surah": 3,
        "ayah": 173,
        "ref": "3:173",
        "why": "\"Cukuplah Allah bagi kami\" — hasbunallah"
      },
      {
        "surah": 64,
        "ayah": 11,
        "ref": "64:11",
        "why": "Tidak ada musibah yang menimpa kecuali dengan izin Allah"
      }
    ]
  },
  {
    "theme": "Syukur",
    "verses": [
      {
        "surah": 14,
        "ayah": 7,
        "ref": "14:7",
        "why": "\"Kalau kalian bersyukur, pasti Aku tambah nikmat untuk kalian\""
      },
      {
        "surah": 2,
        "ayah": 152,
        "ref": "2:152",
        "why": "Ingatlah Aku, Aku pun mengingat kalian"
      },
      {
        "surah": 55,
        "ayah": 13,
        "ref": "55:13",
        "why": "Nikmat Tuhanmu yang mana lagi yang kamu dustakan?"
      }
    ]
  },
  {
    "theme": "Doa yang dikabulkan",
    "verses": [
      {
        "surah": 2,
        "ayah": 186,
        "ref": "2:186",
        "why": "\"Aku dekat — Aku kabulkan doa orang yang berdoa\""
      },
      {
        "surah": 40,
        "ayah": 60,
        "ref": "40:60",
        "why": "\"Berdoalah kepada-Ku, akan Aku kabulkan\""
      },
      {
        "surah": 7,
        "ayah": 55,
        "ref": "7:55",
        "why": "Berdoalah dengan rendah hati, diam-diam saja"
      },
      {
        "surah": 21,
        "ayah": 87,
        "ref": "21:87",
        "why": "Doa Nabi Yunus, dari dalam kegelapan"
      }
    ]
  },
  {
    "theme": "Rahmat & kasih sayang",
    "verses": [
      {
        "surah": 7,
        "ayah": 156,
        "ref": "7:156",
        "why": "\"Rahmat-Ku meliputi segala sesuatu\""
      },
      {
        "surah": 21,
        "ayah": 107,
        "ref": "21:107",
        "why": "Diutus sebagai rahmat bagi seluruh alam"
      },
      {
        "surah": 6,
        "ayah": 54,
        "ref": "6:54",
        "why": "Tuhanmu telah menetapkan kasih sayang atas diri-Nya"
      }
    ]
  },
  {
    "theme": "Harga diri & makna hidup",
    "verses": [
      {
        "surah": 95,
        "ayah": 4,
        "ref": "95:4",
        "why": "Manusia diciptakan dalam bentuk yang sebaik-baiknya"
      },
      {
        "surah": 51,
        "ayah": 56,
        "ref": "51:56",
        "why": "Jin dan manusia diciptakan hanya untuk beribadah"
      },
      {
        "surah": 17,
        "ayah": 70,
        "ref": "17:70",
        "why": "Sungguh Kami telah memuliakan anak cucu Adam"
      }
    ]
  },
  {
    "theme": "Keluarga",
    "verses": [
      {
        "surah": 30,
        "ayah": 21,
        "ref": "30:21",
        "why": "Dia jadikan di antara kalian rasa cinta dan kasih sayang"
      },
      {
        "surah": 17,
        "ayah": 23,
        "ref": "17:23",
        "why": "Berbuat baiklah kepada orang tua"
      },
      {
        "surah": 17,
        "ayah": 24,
        "ref": "17:24",
        "why": "\"Tuhanku, sayangilah mereka seperti mereka merawatku waktu kecil\""
      }
    ]
  },
  {
    "theme": "Iri & membanding-bandingkan",
    "verses": [
      {
        "surah": 4,
        "ayah": 32,
        "ref": "4:32",
        "why": "Jangan menginginkan kelebihan orang lain; mohonlah kepada Allah sebagian dari karunia-Nya."
      }
    ]
  },
  {
    "theme": "Marah",
    "verses": [
      {
        "surah": 41,
        "ayah": 35,
        "ref": "41:35",
        "why": "Membalas keburukan dengan cara yang lebih baik memerlukan kesabaran dan bagian kebaikan yang besar.",
        "codisplay": [
          34,
          35
        ]
      },
      {
        "surah": 3,
        "ayah": 134,
        "ref": "3:134",
        "why": "Mereka yang menahan amarah dan memaafkan orang lain"
      }
    ]
  },
  {
    "theme": "Kesepian",
    "verses": [
      {
        "surah": 50,
        "ayah": 16,
        "ref": "50:16",
        "why": "Allah mengetahui bisikan hatimu dan lebih dekat daripada urat lehermu; tidak ada isi hatimu yang tersembunyi dari-Nya."
      }
    ]
  },
  {
    "theme": "Sakit & kesembuhan",
    "verses": [
      {
        "surah": 26,
        "ayah": 80,
        "ref": "26:80",
        "why": "\"Ketika aku sakit, Tuhankulah yang menyembuhkan aku\" — doa Ibrahim"
      }
    ]
  },
  {
    "theme": "Lisan & gunjingan",
    "verses": [
      {
        "surah": 49,
        "ayah": 12,
        "ref": "49:12",
        "why": "Jauhi prasangka, jangan mencari-cari kesalahan, jangan menggunjing"
      }
    ]
  },
  {
    "theme": "Memaafkan orang lain",
    "verses": [
      {
        "surah": 2,
        "ayah": 263,
        "ref": "2:263",
        "why": "Berkata baik dan memaafkan lebih baik daripada sedekah yang menyakiti hati"
      }
    ]
  },
  {
    "theme": "Sombong & angkuh",
    "verses": [
      {
        "surah": 31,
        "ayah": 18,
        "ref": "31:18",
        "why": "Nasihat Luqman kepada anaknya — jangan berjalan di bumi dengan sombong"
      },
      {
        "surah": 57,
        "ayah": 23,
        "ref": "57:23",
        "why": "Jangan berduka berlebihan atas yang luput dan jangan membanggakan diri atas yang Allah berikan."
      }
    ]
  },
  {
    "theme": "Takut mati",
    "verses": [
      {
        "surah": 29,
        "ayah": 57,
        "ref": "29:57",
        "why": "Setiap yang bernyawa pasti merasakan kematian, lalu dikumpulkan kembali"
      }
    ]
  },
  {
    "theme": "Ragu & iman melemah",
    "verses": [
      {
        "surah": 14,
        "ayah": 27,
        "ref": "14:27",
        "why": "Allah meneguhkan orang beriman dengan kalimat yang teguh di dunia dan akhirat."
      },
      {
        "surah": 18,
        "ayah": 14,
        "ref": "18:14",
        "why": "\"Kami teguhkan hati mereka\" — para pemuda Ashabul Kahfi"
      }
    ]
  },
  {
    "theme": "Harta & tamak",
    "verses": [
      {
        "surah": 2,
        "ayah": 268,
        "ref": "2:268",
        "why": "Setan menakut-nakutimu dengan kemiskinan; Allah menjanjikan ampunan dan karunia"
      },
      {
        "surah": 57,
        "ayah": 20,
        "ref": "57:20",
        "why": "Dunia hanya permainan dan saling membanggakan harta dan anak"
      }
    ]
  },
  {
    "theme": "Orang tua",
    "verses": [
      {
        "surah": 19,
        "ayah": 14,
        "ref": "19:14",
        "why": "Yahya berbakti kepada ibu bapaknya, tidak durhaka"
      },
      {
        "surah": 14,
        "ayah": 41,
        "ref": "14:41",
        "why": "Doa Ibrahim — ampunilah aku dan kedua orang tuaku"
      },
      {
        "surah": 71,
        "ayah": 28,
        "ref": "71:28",
        "why": "Nabi Nuh memohon ampun untuk dirinya, kedua orang tuanya, dan orang-orang beriman"
      }
    ]
  },
  {
    "theme": "Dizalimi",
    "verses": [
      {
        "surah": 4,
        "ayah": 148,
        "ref": "4:148",
        "why": "Orang yang teraniaya boleh menyuarakan apa yang menimpanya"
      }
    ]
  },
  {
    "theme": "Rasa bersalah & dosa",
    "verses": [
      {
        "surah": 4,
        "ayah": 27,
        "ref": "4:27",
        "why": "Allah hendak menerima taubatmu; jangan mengikuti hawa nafsu yang menjauhkanmu."
      }
    ]
  },
  {
    "theme": "Menanti keturunan",
    "verses": [
      {
        "surah": 21,
        "ayah": 89,
        "ref": "21:89",
        "why": "Nabi Zakaria pun pernah memohon keturunan dengan hati yang sama"
      },
      {
        "surah": 3,
        "ayah": 38,
        "ref": "3:38",
        "why": "Allah Maha Mendengar setiap permohonan yang kau bisikkan"
      }
    ]
  },
  {
    "theme": "Menanti jodoh",
    "verses": [
      {
        "surah": 25,
        "ayah": 74,
        "ref": "25:74",
        "why": "Beginilah hamba-hamba-Nya meminta pasangan yang menenteramkan hati"
      }
    ]
  },
  {
    "theme": "Lelah mendidik anak",
    "verses": [
      {
        "surah": 20,
        "ayah": 132,
        "ref": "20:132",
        "why": "Perintahkan keluargamu salat dan bersabarlah menjaganya; Allah-lah yang memberi rezeki."
      },
      {
        "surah": 11,
        "ayah": 115,
        "ref": "11:115",
        "why": "Bersabarlah; Allah tidak menyia-nyiakan pahala orang-orang yang berbuat baik"
      },
      {
        "surah": 14,
        "ayah": 40,
        "ref": "14:40",
        "why": "Doakan anakmu; itu pun bagian dari mendidiknya"
      }
    ]
  },
  {
    "theme": "Anak yang menjauh",
    "verses": [
      {
        "surah": 28,
        "ayah": 56,
        "ref": "28:56",
        "why": "Kamu tidak dapat memberi hidayah kepada orang yang kamu cintai; Allah memberi hidayah, sedangkan tugasmu tetap menasihati, mendoakan, dan memberi teladan."
      }
    ]
  },
  {
    "theme": "Merawat orang tua",
    "verses": [
      {
        "surah": 31,
        "ayah": 14,
        "ref": "31:14",
        "why": "Bersyukurlah kepada Allah dan kepada kedua orang tua; ingatlah beratnya ibu mengandung dan menyapih."
      },
      {
        "surah": 46,
        "ayah": 15,
        "ref": "46:15",
        "why": "Berbuat baiklah kepada orang tua; mohon kekuatan untuk mensyukuri nikmat dan beramal saleh yang Allah ridhai."
      }
    ]
  },
  {
    "theme": "Pertengkaran keluarga",
    "verses": [
      {
        "surah": 41,
        "ayah": 34,
        "ref": "41:34",
        "why": "Balas keburukan dengan kebaikan, permusuhan bisa berubah jadi kedekatan"
      },
      {
        "surah": 8,
        "ayah": 63,
        "ref": "8:63",
        "why": "Hanya Allah yang sanggup menyatukan hati yang saling menjauh"
      }
    ]
  },
  {
    "theme": "Mengasuh sendirian",
    "verses": [
      {
        "surah": 19,
        "ayah": 24,
        "ref": "19:24",
        "why": "Ketika Maryam sendirian dalam kesulitan, Allah menyampaikan kepadanya: jangan bersedih."
      },
      {
        "surah": 28,
        "ayah": 7,
        "ref": "28:7",
        "why": "Allah menenangkan ibu Musa ketika ia takut akan keselamatan anaknya: jangan takut dan jangan bersedih."
      }
    ]
  },
  {
    "theme": "Khawatir masa depan",
    "verses": [
      {
        "surah": 33,
        "ayah": 3,
        "ref": "33:3",
        "why": "Bertawakallah kepada Allah; cukuplah Allah sebagai Pemelihara"
      },
      {
        "surah": 46,
        "ayah": 13,
        "ref": "46:13",
        "why": "Tetap teguh pada Allah, maka tak ada yang perlu ditakutkan"
      },
      {
        "surah": 31,
        "ayah": 34,
        "ref": "31:34",
        "why": "Tak seorang pun mengetahui pasti apa yang akan diusahakannya besok; Allah Maha Mengetahui—maka rencanakan, berikhtiar, dan serahkan hasil kepada-Nya."
      }
    ]
  },
  {
    "theme": "Bingung memilih",
    "verses": [
      {
        "surah": 18,
        "ayah": 24,
        "ref": "18:24",
        "why": "Katakan insya Allah dan mohon agar Tuhan menunjukkan jalan yang lebih dekat kepada kebenaran."
      },
      {
        "surah": 42,
        "ayah": 38,
        "ref": "42:38",
        "why": "Jangan putuskan sendirian; bermusyawarahlah, itu ciri orang beriman"
      }
    ]
  },
  {
    "theme": "Memulai lagi",
    "verses": [
      {
        "surah": 4,
        "ayah": 100,
        "ref": "4:100",
        "why": "Siapa yang berhijrah di jalan Allah akan mendapati tempat yang luas dan rezeki; niat dan arah hijrahnya harus karena Allah."
      }
    ]
  },
  {
    "theme": "Harapan",
    "verses": [
      {
        "surah": 93,
        "ayah": 5,
        "ref": "93:5",
        "why": "Tuhanmu akan memberi kepadamu hingga engkau ridha—penghiburan Allah kepada Nabi-Nya."
      }
    ]
  },
  {
    "theme": "Bahagia",
    "verses": [
      {
        "surah": 10,
        "ayah": 58,
        "ref": "10:58",
        "why": "Bergembiralah dengan karunia dan rahmat Allah"
      },
      {
        "surah": 27,
        "ayah": 19,
        "ref": "27:19",
        "why": "Sulaiman tersenyum, lalu memohon agar pandai mensyukuri nikmat-Nya"
      },
      {
        "surah": 93,
        "ayah": 11,
        "ref": "93:11",
        "why": "Saat bahagia, sebut dan syukuri nikmat Tuhanmu"
      }
    ]
  },
  {
    "theme": "Menua",
    "verses": [
      {
        "surah": 30,
        "ayah": 54,
        "ref": "30:54",
        "why": "Lemah, kuat, lalu lemah lagi — semua dalam rencana-Nya"
      }
    ]
  },
  {
    "theme": "Sakit menahun",
    "verses": [
      {
        "surah": 21,
        "ayah": 83,
        "ref": "21:83",
        "why": "Doa Ayyub: penyakit ini menimpaku, dan Engkau Maha Penyayang"
      },
      {
        "surah": 21,
        "ayah": 84,
        "ref": "21:84",
        "why": "Allah mengabulkan doa Ayyub dan mengangkat penderitaannya—kisah rahmat dan harapan, bukan pola hasil yang dijanjikan kepada setiap orang."
      },
      {
        "surah": 10,
        "ayah": 57,
        "ref": "10:57",
        "why": "Al-Qur’an adalah pelajaran dan penawar bagi penyakit dalam dada, sekalipun kesembuhan jasmani tetap memerlukan ikhtiar dan ketetapan Allah."
      }
    ]
  },
  {
    "theme": "Perceraian",
    "verses": [
      {
        "surah": 4,
        "ayah": 130,
        "ref": "4:130",
        "why": "Jika berpisah, Allah mencukupi keduanya dari karunia-Nya masing-masing"
      },
      {
        "surah": 2,
        "ayah": 237,
        "ref": "2:237",
        "why": "Berpisahlah tanpa melupakan kebaikan yang pernah ada di antara kalian"
      }
    ]
  },
  {
    "theme": "Dikhianati",
    "verses": [
      {
        "surah": 12,
        "ayah": 18,
        "ref": "12:18",
        "why": "Saat orang terdekat berdusta, kesabaran yang indah adalah jalannya"
      },
      {
        "surah": 12,
        "ayah": 90,
        "ref": "12:90",
        "why": "Yusuf dikhianati saudaranya, namun Allah tak menyia-nyiakan orang yang bersabar"
      },
      {
        "surah": 40,
        "ayah": 19,
        "ref": "40:19",
        "why": "Allah mengetahui pandangan yang berkhianat dan apa yang disembunyikan hati."
      }
    ]
  },
  {
    "theme": "Ditinggalkan",
    "verses": [
      {
        "surah": 93,
        "ayah": 6,
        "ref": "93:6",
        "why": "Bukankah Dia mendapatimu yatim lalu melindungimu?—penghiburan Allah kepada Nabi-Nya yang menumbuhkan harapan akan pemeliharaan-Nya."
      }
    ]
  },
  {
    "theme": "Rindu",
    "verses": [
      {
        "surah": 12,
        "ayah": 84,
        "ref": "12:84",
        "why": "Bahkan seorang nabi menangis sampai matanya memutih karena rindu"
      },
      {
        "surah": 12,
        "ayah": 87,
        "ref": "12:87",
        "why": "Selama merindu, jangan pernah berputus asa dari rahmat Allah"
      },
      {
        "surah": 12,
        "ayah": 96,
        "ref": "12:96",
        "why": "Kisah Ya’qub berakhir dengan kabar gembira; jadikan ia teladan berharap kepada Allah, bukan janji hasil yang sama bagi semua orang."
      }
    ]
  },
  {
    "theme": "Kekurangan",
    "verses": [
      {
        "surah": 93,
        "ayah": 8,
        "ref": "93:8",
        "why": "Dia mendapatimu kekurangan lalu memberi kecukupan—penghiburan kepada Nabi yang menumbuhkan harapan, bukan janji cepat kaya bagi setiap orang."
      },
      {
        "surah": 67,
        "ayah": 15,
        "ref": "67:15",
        "why": "Bumi dibentangkan untukmu; melangkahlah, rezeki-Nya ada di sana"
      }
    ]
  },
  {
    "theme": "Cemas soal uang",
    "verses": [
      {
        "surah": 15,
        "ayah": 21,
        "ref": "15:21",
        "why": "Segala sesuatu memiliki khazanah di sisi Allah dan diturunkan dengan ukuran tertentu; tetaplah berikhtiar secara halal."
      }
    ]
  },
  {
    "theme": "Pelit",
    "verses": [
      {
        "surah": 17,
        "ayah": 29,
        "ref": "17:29",
        "why": "Jangan menggenggam terlalu erat, jangan pula menghambur; ambil tengahnya"
      },
      {
        "surah": 64,
        "ayah": 16,
        "ref": "64:16",
        "why": "Bertakwalah sesanggupmu; berilah, itu kebaikan untuk dirimu sendiri"
      }
    ]
  },
  {
    "theme": "Tidak pernah merasa cukup",
    "verses": [
      {
        "surah": 102,
        "ayah": 1,
        "ref": "102:1",
        "why": "Berlomba memperbanyak dan bermegah-megahan telah melalaikanmu."
      },
      {
        "surah": 63,
        "ayah": 9,
        "ref": "63:9",
        "why": "Jangan biarkan harta dan anak melalaikanmu dari mengingat-Nya"
      }
    ]
  },
  {
    "theme": "Merasa cukup",
    "verses": [
      {
        "surah": 28,
        "ayah": 60,
        "ref": "28:60",
        "why": "Yang ada di sisi Allah lebih baik dan lebih kekal"
      },
      {
        "surah": 16,
        "ayah": 96,
        "ref": "16:96",
        "why": "Milikmu akan habis; yang di sisi Allah tetap kekal"
      }
    ]
  },
  {
    "theme": "Sedekah",
    "verses": [
      {
        "surah": 2,
        "ayah": 261,
        "ref": "2:261",
        "why": "Satu biji yang kamu tanam menjadi tujuh tangkai berbuah"
      },
      {
        "surah": 2,
        "ayah": 274,
        "ref": "2:274",
        "why": "Yang memberi diam-diam maupun terang: tak ada takut, tak ada sedih"
      },
      {
        "surah": 34,
        "ayah": 39,
        "ref": "34:39",
        "why": "Apa yang kamu infakkan, Allah menggantinya menurut hikmah-Nya; Dia sebaik-baik Pemberi rezeki."
      }
    ]
  },
  {
    "theme": "Iri melihat kekayaan orang",
    "verses": [
      {
        "surah": 20,
        "ayah": 131,
        "ref": "20:131",
        "why": "Jangan tujukan matamu ke milik orang lain; itu ujian"
      },
      {
        "surah": 15,
        "ayah": 88,
        "ref": "15:88",
        "why": "Jangan melirik milik mereka, jangan pula bersedih karenanya"
      }
    ]
  },
  {
    "theme": "Malu",
    "verses": [
      {
        "surah": 25,
        "ayah": 70,
        "ref": "25:70",
        "why": "Bagi yang kembali, Allah menukar dosa-dosa itu dengan pahala"
      },
      {
        "surah": 11,
        "ayah": 114,
        "ref": "11:114",
        "why": "Kebaikan menghapus keburukan; dosa besar dan hak manusia tetap memerlukan taubat serta perbaikan khusus."
      },
      {
        "surah": 40,
        "ayah": 7,
        "ref": "40:7",
        "why": "Para malaikat pemikul ‘Arsy memohonkan ampun bagi orang beriman yang bertaubat dan mengikuti jalan Allah."
      }
    ]
  },
  {
    "theme": "Menyesal",
    "verses": [
      {
        "surah": 2,
        "ayah": 37,
        "ref": "2:37",
        "why": "Adam pun pernah jatuh, dan taubatnya diterima Allah"
      },
      {
        "surah": 3,
        "ayah": 133,
        "ref": "3:133",
        "why": "Jangan berlama-lama di masa lalu; bergegaslah menuju ampunan-Nya"
      },
      {
        "surah": 5,
        "ayah": 39,
        "ref": "5:39",
        "why": "Sesudah berbuat zalim, bertaubatlah dan perbaikilah diri; bila menyangkut hak manusia, kembalikan hak dan mintalah maaf."
      }
    ]
  },
  {
    "theme": "Minder",
    "verses": [
      {
        "surah": 49,
        "ayah": 11,
        "ref": "49:11",
        "why": "Yang direndahkan orang bisa jadi lebih baik di sisi Allah"
      },
      {
        "surah": 49,
        "ayah": 13,
        "ref": "49:13",
        "why": "Ukuran kemuliaan bukan status, melainkan takwa di sisi Allah"
      }
    ]
  },
  {
    "theme": "Merasa tidak berguna",
    "verses": [
      {
        "surah": 21,
        "ayah": 94,
        "ref": "21:94",
        "why": "Tidak ada satu pun kebaikanmu yang disia-siakan Allah"
      },
      {
        "surah": 99,
        "ayah": 7,
        "ref": "99:7",
        "why": "Sekecil debu pun kebaikanmu tetap terlihat dan berbalas"
      },
      {
        "surah": 64,
        "ayah": 3,
        "ref": "64:3",
        "why": "Allah membentukmu dengan baik menurut hikmah-Nya; kepada-Nya seluruh perjalanan kembali."
      }
    ]
  },
  {
    "theme": "Merasa tidak dicintai",
    "verses": [
      {
        "surah": 93,
        "ayah": 3,
        "ref": "93:3",
        "why": "Tuhanmu tidak meninggalkan dan tidak membenci Nabi-Nya—ayat penghiburan bagi hati yang merasa jauh dari kasih Allah."
      },
      {
        "surah": 3,
        "ayah": 31,
        "ref": "3:31",
        "why": "Ikutilah Rasulullah; Allah akan mencintai dan mengampuni dosa-dosamu."
      },
      {
        "surah": 11,
        "ayah": 90,
        "ref": "11:90",
        "why": "Mohonlah ampun dan bertaubatlah kepada-Nya; Tuhanku Maha Penyayang lagi Maha Pengasih."
      }
    ]
  },
  {
    "theme": "Hampa",
    "verses": [
      {
        "surah": 16,
        "ayah": 97,
        "ref": "16:97",
        "why": "Iman dan amal kecil pun membuahkan kehidupan yang baik"
      },
      {
        "surah": 23,
        "ayah": 115,
        "ref": "23:115",
        "why": "Kamu tidak diciptakan tanpa maksud; hidupmu punya tujuan"
      },
      {
        "surah": 67,
        "ayah": 2,
        "ref": "67:2",
        "why": "Hidup dan mati diadakan agar terlihat siapa terbaik amalnya"
      }
    ]
  },
  {
    "theme": "Ingin berubah",
    "verses": [
      {
        "surah": 20,
        "ayah": 82,
        "ref": "20:82",
        "why": "Bertaubat, beramal, lalu bertahan di jalan itu — Allah mengampuni"
      },
      {
        "surah": 29,
        "ayah": 69,
        "ref": "29:69",
        "why": "Orang yang bersungguh-sungguh di jalan Kami akan Kami tunjukkan jalan-jalan Kami; Allah bersama orang yang berbuat baik."
      }
    ]
  },
  {
    "theme": "Direndahkan",
    "verses": [
      {
        "surah": 33,
        "ayah": 58,
        "ref": "33:58",
        "why": "Menyakiti orang beriman tanpa kesalahan yang mereka lakukan adalah fitnah dan dosa yang nyata."
      },
      {
        "surah": 3,
        "ayah": 186,
        "ref": "3:186",
        "why": "Kamu akan mendengar banyak ucapan menyakitkan; sabar dan takwa adalah keteguhan yang besar."
      }
    ]
  },
  {
    "theme": "Difitnah",
    "verses": [
      {
        "surah": 33,
        "ayah": 69,
        "ref": "33:69",
        "why": "Musa pun difitnah, lalu Allah sendiri yang membersihkannya"
      },
      {
        "surah": 24,
        "ayah": 11,
        "ref": "24:11",
        "why": "Dalam peristiwa ifk, Allah membersihkan tuduhan dan menampakkan hikmah; jangan menjanjikan bahwa setiap fitnah akan terasa baik atau selesai dengan cara yang sama."
      }
    ]
  },
  {
    "theme": "Menyimpan benci",
    "verses": [
      {
        "surah": 5,
        "ayah": 8,
        "ref": "5:8",
        "why": "Jangan biarkan bencimu membuatmu berlaku tidak adil kepadanya"
      },
      {
        "surah": 17,
        "ayah": 53,
        "ref": "17:53",
        "why": "Jawablah celaan dengan kata terbaik; setan senang mengadu domba"
      }
    ]
  },
  {
    "theme": "Ingin membalas",
    "verses": [
      {
        "surah": 42,
        "ayah": 43,
        "ref": "42:43",
        "why": "Sabar dan memaafkan itu tanda hati yang teguh, bukan lemah"
      },
      {
        "surah": 42,
        "ayah": 40,
        "ref": "42:40",
        "why": "Kamu berhak membalas setimpal, tapi pahala pemaaf ditanggung Allah"
      },
      {
        "surah": 12,
        "ayah": 92,
        "ref": "12:92",
        "why": "Yusuf berkuasa membalas, namun ia memilih berkata: tidak ada cercaan"
      }
    ]
  },
  {
    "theme": "Kehilangan sahabat",
    "verses": [
      {
        "surah": 4,
        "ayah": 69,
        "ref": "4:69",
        "why": "Ketaatan mengantarkan kepada kebersamaan dengan para nabi, siddiq, syuhada, dan orang saleh—mereka sebaik-baik teman."
      }
    ]
  },
  {
    "theme": "Masalah dengan tetangga",
    "verses": [
      {
        "surah": 4,
        "ayah": 36,
        "ref": "4:36",
        "why": "Berbuat baik kepada tetangga dekat dan jauh, itu perintah Allah"
      },
      {
        "surah": 49,
        "ayah": 6,
        "ref": "49:6",
        "why": "Jika datang berita dari sumber yang tidak dapat dipercaya, telitilah agar tidak mencelakakan orang lalu menyesal."
      },
      {
        "surah": 24,
        "ayah": 27,
        "ref": "24:27",
        "why": "Menghormati batas rumah orang lain menjaga damainya bertetangga"
      }
    ]
  },
  {
    "theme": "Ingin berdamai",
    "verses": [
      {
        "surah": 49,
        "ayah": 10,
        "ref": "49:10",
        "why": "Kalian bersaudara; damaikanlah, semoga kalian diberi rahmat"
      },
      {
        "surah": 4,
        "ayah": 114,
        "ref": "4:114",
        "why": "Mendamaikan yang berselisih adalah bicara paling bernilai di sisi Allah"
      }
    ]
  },
  {
    "theme": "Putus asa",
    "verses": [
      {
        "surah": 42,
        "ayah": 28,
        "ref": "42:28",
        "why": "Allah menurunkan hujan setelah manusia berputus asa dan menyebarkan rahmat-Nya—tanda keluasan kuasa-Nya."
      },
      {
        "surah": 12,
        "ayah": 110,
        "ref": "12:110",
        "why": "Ketika para rasul tidak lagi berharap kaumnya beriman dan mereka didustakan, pertolongan Allah datang."
      }
    ]
  },
  {
    "theme": "Marah pada takdir",
    "verses": [
      {
        "surah": 57,
        "ayah": 22,
        "ref": "57:22",
        "why": "Tidak ada yang menimpamu tanpa sudah tercatat sebelum dunia ada"
      },
      {
        "surah": 9,
        "ayah": 51,
        "ref": "9:51",
        "why": "Tidak akan menimpa kami kecuali apa yang Allah tetapkan bagi kami; Dia Pelindung kami, maka kepada-Nya orang beriman bertawakal."
      }
    ]
  },
  {
    "theme": "Doa tidak dijawab",
    "verses": [
      {
        "surah": 19,
        "ayah": 4,
        "ref": "19:4",
        "why": "Zakaria tetap memohon kepada Allah meski tubuhnya lemah dan rambutnya beruban; doa tidak menuntut hasil yang segera."
      },
      {
        "surah": 21,
        "ayah": 90,
        "ref": "21:90",
        "why": "Allah mengabulkan doa Zakaria dan memperbaiki keadaan keluarganya—kisah harapan, bukan pola hasil yang wajib terulang."
      },
      {
        "surah": 27,
        "ayah": 62,
        "ref": "27:62",
        "why": "Siapakah yang mengabulkan doa orang yang terdesak dan menghilangkan kesusahan selain Allah?"
      }
    ]
  },
  {
    "theme": "Merasa jauh dari Allah",
    "verses": [
      {
        "surah": 57,
        "ayah": 4,
        "ref": "57:4",
        "why": "Allah mengetahui kalian di mana pun berada; tidak ada keadaanmu yang luput dari pengawasan-Nya."
      },
      {
        "surah": 3,
        "ayah": 8,
        "ref": "3:8",
        "why": "Doa bagi hati yang takut menjauh setelah pernah diberi petunjuk"
      }
    ]
  },
  {
    "theme": "Takut riya atau munafik",
    "verses": [
      {
        "surah": 23,
        "ayah": 60,
        "ref": "23:60",
        "why": "Mereka beramal sambil takut karena akan kembali kepada Tuhan.",
        "codisplay": [
          57,
          61
        ]
      },
      {
        "surah": 23,
        "ayah": 61,
        "ref": "23:61",
        "why": "Mereka itulah yang bersegera dalam kebaikan dan menjadi yang terdepan melakukannya.",
        "codisplay": [
          57,
          61
        ]
      },
      {
        "surah": 4,
        "ayah": 146,
        "ref": "4:146",
        "why": "Orang yang bertaubat, memperbaiki diri, berpegang teguh kepada Allah, dan mengikhlaskan agama akan bersama orang beriman."
      }
    ]
  },
  {
    "theme": "Susah istiqamah",
    "verses": [
      {
        "surah": 73,
        "ayah": 20,
        "ref": "73:20",
        "why": "Allah mengetahui keterbatasan kalian dalam salat malam, lalu memberi keringanan; lakukan yang mampu secara konsisten."
      }
    ]
  },
  {
    "theme": "Lelah & jenuh",
    "verses": [
      {
        "surah": 94,
        "ayah": 2,
        "ref": "94:2",
        "why": "Bukankah Kami telah melapangkan dadamu dan mengangkat bebanmu?—penghiburan Allah kepada Nabi-Nya."
      },
      {
        "surah": 78,
        "ayah": 9,
        "ref": "78:9",
        "why": "Tidurmu bukan kelemahan, itu penenang yang Allah sediakan"
      },
      {
        "surah": 28,
        "ayah": 73,
        "ref": "28:73",
        "why": "Malam untuk beristirahat itu rahmat, bukan waktu yang terbuang"
      }
    ]
  },
  {
    "theme": "Kewalahan",
    "verses": [
      {
        "surah": 4,
        "ayah": 28,
        "ref": "4:28",
        "why": "Allah tahu manusia diciptakan lemah, dan Dia meringankan bebannya"
      },
      {
        "surah": 23,
        "ayah": 62,
        "ref": "23:62",
        "why": "Tidak ada yang dibebani di luar kemampuannya, termasuk kamu"
      }
    ]
  },
  {
    "theme": "Malas & menunda",
    "verses": [
      {
        "surah": 92,
        "ayah": 7,
        "ref": "92:7",
        "why": "Bagi yang memberi, bertakwa, dan membenarkan kebaikan, Allah memudahkan jalan menuju kemudahan.",
        "codisplay": [
          5,
          7
        ]
      }
    ]
  },
  {
    "theme": "Kehilangan pekerjaan",
    "verses": [
      {
        "surah": 29,
        "ayah": 62,
        "ref": "29:62",
        "why": "Allah melapangkan dan menyempitkan rezeki bagi siapa yang Dia kehendaki; Dia mengetahui keadaan hamba-hamba-Nya."
      },
      {
        "surah": 42,
        "ayah": 12,
        "ref": "42:12",
        "why": "Milik Allah kunci-kunci langit dan bumi; Dia melapangkan dan menyempitkan rezeki menurut ilmu-Nya."
      }
    ]
  },
  {
    "theme": "Bingung arah hidup",
    "verses": [
      {
        "surah": 1,
        "ayah": 6,
        "ref": "1:6",
        "why": "Doa paling sederhana saat tak tahu harus ke mana"
      }
    ]
  },
  {
    "theme": "Stres ujian & belajar",
    "verses": [
      {
        "surah": 20,
        "ayah": 26,
        "ref": "20:26",
        "why": "Mudahkanlah urusanku, lepaskan kekakuan lidahku, agar mereka memahami ucapanku.",
        "codisplay": [
          25,
          28
        ]
      },
      {
        "surah": 20,
        "ayah": 25,
        "ref": "20:25",
        "why": "Ya Tuhanku, lapangkanlah dadaku.",
        "codisplay": [
          25,
          28
        ]
      },
      {
        "surah": 96,
        "ayah": 5,
        "ref": "96:5",
        "why": "Dia yang mengajari manusia apa yang belum diketahuinya"
      }
    ]
  },
  {
    "theme": "Usaha terasa tak cukup",
    "verses": [
      {
        "surah": 3,
        "ayah": 195,
        "ref": "3:195",
        "why": "Allah tidak menyia-nyiakan amal siapa pun, laki-laki maupun perempuan"
      },
      {
        "surah": 4,
        "ayah": 40,
        "ref": "4:40",
        "why": "Sebesar zarrah pun tak hilang, malah dilipatgandakan"
      },
      {
        "surah": 18,
        "ayah": 30,
        "ref": "18:30",
        "why": "Yang kamu kerjakan dengan baik tidak akan disia-siakan"
      }
    ]
  },
  {
    "theme": "Godaan & hawa nafsu",
    "verses": [
      {
        "surah": 2,
        "ayah": 183,
        "ref": "2:183",
        "why": "Puasa diwajibkan agar kamu bertakwa; ia melatih pengendalian diri di bawah ketaatan kepada Allah."
      }
    ]
  },
  {
    "theme": "Pernikahan & pasangan",
    "verses": [
      {
        "surah": 2,
        "ayah": 187,
        "ref": "2:187",
        "why": "Mereka adalah pakaian bagimu dan kamu adalah pakaian bagi mereka—kedekatan, perlindungan, dan kehormatan yang timbal balik."
      }
    ]
  },
  {
    "theme": "Patah hati",
    "verses": [
      {
        "surah": 2,
        "ayah": 216,
        "ref": "2:216",
        "why": "Yang kamu tolak bisa jadi baik; Allah tahu, kamu tidak"
      },
      {
        "surah": 10,
        "ayah": 57,
        "ref": "10:57",
        "why": "Al-Qur’an adalah pelajaran dan penawar bagi penyakit dalam dada, sekalipun kesembuhan jasmani tetap memerlukan ikhtiar dan ketetapan Allah."
      }
    ]
  },
  {
    "theme": "Ditolak",
    "verses": [
      {
        "surah": 16,
        "ayah": 127,
        "ref": "16:127",
        "why": "Bersabarlah dengan pertolongan Allah; jangan bersedih dan jangan bersempit dada karena tipu daya mereka."
      }
    ]
  },
  {
    "theme": "Merantau",
    "verses": [
      {
        "surah": 106,
        "ayah": 4,
        "ref": "106:4",
        "why": "Dalam perjalanan dagang Quraisy, Allah mengingatkan nikmat pangan dan keamanan; bersyukurlah kepada Tuhan pemilik Ka’bah.",
        "codisplay": [
          1,
          4
        ]
      }
    ]
  },
  {
    "theme": "Merasa terlalu banyak dosa",
    "verses": [
      {
        "surah": 4,
        "ayah": 17,
        "ref": "4:17",
        "why": "Bertaubatlah segera setelah berbuat salah; Allah menerima taubat orang yang kembali sebelum terlambat."
      }
    ]
  }
] as const;
