// GENERATED by `bun run app:themes` — do not edit. Source: src/review/problem-verses.ts.
//
// Path A from issue 07: the cheap, honest version of "concept navigation" — surfaces the
// EXISTING 12-theme lexicon (already used to score chat retrieval) as a browsable index, rather
// than committing to the full LLM-extracted knowledge graph the original spec envisioned. Only
// covers the 55 hand-curated verses today; each verse's actual text is fetched from the existing
// per-surah shard (web/public/surah/{n}.json), not duplicated here.

export interface ThemeVerse {
  readonly surah: number;
  readonly ayah: number;
  readonly ref: string;
  readonly why: string;
}

export interface ThemeGroup {
  readonly theme: string;
  readonly verses: readonly ThemeVerse[];
}

export const THEME_INDEX: readonly ThemeGroup[] = [
  {
    "theme": "Kesulitan & kelapangan",
    "verses": [
      {
        "surah": 94,
        "ayah": 5,
        "ref": "94:5",
        "why": "Ayat penghiburan — bersama kesulitan ada kemudahan"
      },
      {
        "surah": 94,
        "ayah": 6,
        "ref": "94:6",
        "why": "Diulang dua kali — itu yang membuatnya janji, bukan kebetulan"
      },
      {
        "surah": 65,
        "ayah": 7,
        "ref": "65:7",
        "why": "Allah akan memberi kemudahan setelah kesulitan"
      },
      {
        "surah": 2,
        "ayah": 286,
        "ref": "2:286",
        "why": "Allah tidak membebani seseorang melebihi kesanggupannya"
      },
      {
        "surah": 65,
        "ayah": 2,
        "ref": "65:2",
        "why": "Jalan keluar bagi orang yang bertakwa"
      },
      {
        "surah": 2,
        "ayah": 214,
        "ref": "2:214",
        "why": "\"Kapan datang pertolongan Allah?\" — jeritan orang yang diuji"
      }
    ]
  },
  {
    "theme": "Cemas & takut",
    "verses": [
      {
        "surah": 13,
        "ayah": 28,
        "ref": "13:28",
        "why": "Hati menjadi tenang dengan mengingat Allah"
      },
      {
        "surah": 3,
        "ayah": 139,
        "ref": "3:139",
        "why": "Jangan lemah, jangan bersedih"
      },
      {
        "surah": 9,
        "ayah": 40,
        "ref": "9:40",
        "why": "\"Jangan sedih — Allah bersama kita\""
      },
      {
        "surah": 20,
        "ayah": 46,
        "ref": "20:46",
        "why": "\"Jangan takut. Aku bersama kalian, mendengar dan melihat\""
      },
      {
        "surah": 41,
        "ayah": 30,
        "ref": "41:30",
        "why": "Para malaikat: \"jangan takut, jangan bersedih\""
      },
      {
        "surah": 2,
        "ayah": 112,
        "ref": "2:112",
        "why": "Tidak ada rasa takut pada mereka, dan mereka tidak bersedih hati"
      }
    ]
  },
  {
    "theme": "Duka & kehilangan",
    "verses": [
      {
        "surah": 2,
        "ayah": 156,
        "ref": "2:156",
        "why": "Inna lillahi wa inna ilaihi raji'un — dibaca di setiap kematian"
      },
      {
        "surah": 2,
        "ayah": 155,
        "ref": "2:155",
        "why": "\"Kami pasti menguji kalian… sampaikan kabar gembira bagi yang sabar\""
      },
      {
        "surah": 2,
        "ayah": 157,
        "ref": "2:157",
        "why": "Keberkahan dan rahmat bagi mereka yang bertahan"
      },
      {
        "surah": 12,
        "ayah": 86,
        "ref": "12:86",
        "why": "Ya'qub: \"Hanya kepada Allah aku mengadukan kesedihanku\""
      },
      {
        "surah": 3,
        "ayah": 185,
        "ref": "3:185",
        "why": "Setiap yang bernyawa akan merasakan mati"
      },
      {
        "surah": 21,
        "ayah": 35,
        "ref": "21:35",
        "why": "Diuji lewat hal buruk dan hal baik — dua-duanya ujian"
      }
    ]
  },
  {
    "theme": "Kesabaran",
    "verses": [
      {
        "surah": 2,
        "ayah": 153,
        "ref": "2:153",
        "why": "Mintalah pertolongan dengan sabar dan salat"
      },
      {
        "surah": 39,
        "ayah": 10,
        "ref": "39:10",
        "why": "Orang sabar diberi pahala tanpa batas"
      },
      {
        "surah": 3,
        "ayah": 200,
        "ref": "3:200",
        "why": "Sabar, kuatkan kesabaranmu, jangan goyah"
      },
      {
        "surah": 103,
        "ayah": 3,
        "ref": "103:3",
        "why": "Al-'Asr — mereka yang saling menasihati untuk sabar"
      },
      {
        "surah": 8,
        "ayah": 46,
        "ref": "8:46",
        "why": "Allah bersama orang-orang yang sabar"
      }
    ]
  },
  {
    "theme": "Ampunan & putus asa",
    "verses": [
      {
        "surah": 39,
        "ayah": 53,
        "ref": "39:53",
        "why": "\"Jangan berputus asa dari rahmat Allah\" — ayat untuk yang merasa kotor"
      },
      {
        "surah": 3,
        "ayah": 135,
        "ref": "3:135",
        "why": "Siapa yang mengampuni dosa selain Allah?"
      },
      {
        "surah": 66,
        "ayah": 8,
        "ref": "66:8",
        "why": "Kembalilah kepada Allah dengan tobat yang tulus"
      },
      {
        "surah": 24,
        "ayah": 22,
        "ref": "24:22",
        "why": "Maafkan, dan lapangkan dadamu"
      },
      {
        "surah": 4,
        "ayah": 110,
        "ref": "4:110",
        "why": "Siapa pun yang berbuat salah lalu minta ampun"
      },
      {
        "surah": 42,
        "ayah": 25,
        "ref": "42:25",
        "why": "Dia menerima tobat dari hamba-hamba-Nya"
      }
    ]
  },
  {
    "theme": "Rezeki & utang",
    "verses": [
      {
        "surah": 65,
        "ayah": 3,
        "ref": "65:3",
        "why": "Rezeki dari arah yang tidak disangka-sangka"
      },
      {
        "surah": 11,
        "ayah": 6,
        "ref": "11:6",
        "why": "Semua makhluk sudah dijamin rezekinya oleh Allah"
      },
      {
        "surah": 51,
        "ayah": 22,
        "ref": "51:22",
        "why": "Di langit ada rezekimu"
      },
      {
        "surah": 29,
        "ayah": 60,
        "ref": "29:60",
        "why": "Allah yang memberi rezeki kepadanya dan kepadamu"
      },
      {
        "surah": 2,
        "ayah": 280,
        "ref": "2:280",
        "why": "Kalau yang berutang lagi kesulitan, beri dia waktu"
      },
      {
        "surah": 94,
        "ayah": 7,
        "ref": "94:7",
        "why": "Kalau sudah selesai, kerjakan yang berikutnya"
      }
    ]
  },
  {
    "theme": "Tawakal",
    "verses": [
      {
        "surah": 3,
        "ayah": 159,
        "ref": "3:159",
        "why": "Kalau sudah bertekad, bertawakallah kepada Allah"
      },
      {
        "surah": 8,
        "ayah": 2,
        "ref": "8:2",
        "why": "Hatinya bergetar, imannya bertambah, lalu ia bertawakal"
      },
      {
        "surah": 3,
        "ayah": 173,
        "ref": "3:173",
        "why": "\"Cukuplah Allah bagi kami\" — hasbunallah"
      },
      {
        "surah": 64,
        "ayah": 11,
        "ref": "64:11",
        "why": "Tidak ada musibah yang menimpa kecuali dengan izin Allah"
      }
    ]
  },
  {
    "theme": "Syukur",
    "verses": [
      {
        "surah": 14,
        "ayah": 7,
        "ref": "14:7",
        "why": "\"Kalau kalian bersyukur, pasti Aku tambah nikmat untuk kalian\""
      },
      {
        "surah": 2,
        "ayah": 152,
        "ref": "2:152",
        "why": "Ingatlah Aku, Aku pun mengingat kalian"
      },
      {
        "surah": 55,
        "ayah": 13,
        "ref": "55:13",
        "why": "Nikmat Tuhanmu yang mana lagi yang kamu dustakan?"
      }
    ]
  },
  {
    "theme": "Doa yang dikabulkan",
    "verses": [
      {
        "surah": 2,
        "ayah": 186,
        "ref": "2:186",
        "why": "\"Aku dekat — Aku kabulkan doa orang yang berdoa\""
      },
      {
        "surah": 40,
        "ayah": 60,
        "ref": "40:60",
        "why": "\"Berdoalah kepada-Ku, akan Aku kabulkan\""
      },
      {
        "surah": 7,
        "ayah": 55,
        "ref": "7:55",
        "why": "Berdoalah dengan rendah hati, diam-diam saja"
      },
      {
        "surah": 21,
        "ayah": 87,
        "ref": "21:87",
        "why": "Doa Nabi Yunus, dari dalam kegelapan"
      }
    ]
  },
  {
    "theme": "Rahmat & kasih sayang",
    "verses": [
      {
        "surah": 7,
        "ayah": 156,
        "ref": "7:156",
        "why": "\"Rahmat-Ku meliputi segala sesuatu\""
      },
      {
        "surah": 21,
        "ayah": 107,
        "ref": "21:107",
        "why": "Diutus sebagai rahmat bagi seluruh alam"
      },
      {
        "surah": 6,
        "ayah": 54,
        "ref": "6:54",
        "why": "Tuhanmu telah menetapkan kasih sayang atas diri-Nya"
      }
    ]
  },
  {
    "theme": "Harga diri & makna hidup",
    "verses": [
      {
        "surah": 95,
        "ayah": 4,
        "ref": "95:4",
        "why": "Manusia diciptakan dalam bentuk yang sebaik-baiknya"
      },
      {
        "surah": 51,
        "ayah": 56,
        "ref": "51:56",
        "why": "Jin dan manusia diciptakan hanya untuk beribadah"
      },
      {
        "surah": 17,
        "ayah": 70,
        "ref": "17:70",
        "why": "Sungguh Kami telah memuliakan anak cucu Adam"
      }
    ]
  },
  {
    "theme": "Keluarga",
    "verses": [
      {
        "surah": 30,
        "ayah": 21,
        "ref": "30:21",
        "why": "Dia jadikan di antara kalian rasa cinta dan kasih sayang"
      },
      {
        "surah": 17,
        "ayah": 23,
        "ref": "17:23",
        "why": "Berbuat baiklah kepada orang tua"
      },
      {
        "surah": 17,
        "ayah": 24,
        "ref": "17:24",
        "why": "\"Tuhanku, sayangilah mereka seperti mereka merawatku waktu kecil\""
      }
    ]
  }
] as const;
