/**
 * Theme browsing — concept navigation, Path A.
 *
 * Issue 07 (`.scratch/nur-phase2-trust-and-depth/issues/07-concept-cross-linking.md`) asked for
 * concept-to-concept navigation like the original design spec envisioned (an LLM-extracted
 * knowledge graph). That was never built, and building it means putting an LLM into an ingest
 * pipeline that has been deliberately zero-LLM from day one — a real architectural bet, not a
 * quick win. This is the cheap, honest alternative: surface the 12-theme lexicon that ALREADY
 * exists (`src/review/problem-verses.ts`, already used to score chat retrieval) as something a
 * reader can browse directly, and see whether concept-style navigation gets used at all before
 * committing to anything bigger.
 *
 * Only the 55 hand-curated verses are covered — `THEME_INDEX` (generated by `bun run
 * app:themes`) says so honestly; a verse outside it simply isn't reachable from here. Each
 * verse's actual text comes from the SAME shard fetch the reading surface already uses — no new
 * data path, no duplicated corpus, no risk of the honesty contract forking between surfaces.
 *
 * Renders into the SAME #read container read.ts uses, and registers cards through
 * `registerReadCard()` rather than keeping a separate map — so read.ts's existing copy/share
 * handler covers this surface too, instead of a third, duplicated click listener.
 */
import { loadAyah, ShardError, surahMeta } from "./quran.ts";
import { bindActs, clearReadCards, registerReadCard } from "./read.ts";
import { THEME_INDEX } from "./theme-index.ts";
import { esc, fromShard, verseEl, type VerseCard } from "./verse.ts";

const say = (msg: string): void => {
  const live = document.getElementById("live");
  if (live) live.textContent = msg;
};

export const slugify = (theme: string): string =>
  theme
    .toLowerCase()
    .replace(/&/g, "dan")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const bySlug = (slug: string) => THEME_INDEX.find((g) => slugify(g.theme) === slug);

const backEl = (): string =>
  `<a class="back back-top" href="#/tema"><span aria-hidden="true">←</span> Kembali ke daftar tema</a>`;

/** All 12 themes, from the inlined index — zero network. */
export function renderThemeIndex(mount: HTMLElement): void {
  bindActs();
  clearReadCards();

  mount.innerHTML = `
    <div class="read-index">
      <header class="read-intro">
        <h1>Baca berdasarkan tema</h1>
        <p>${THEME_INDEX.length} tema, dari ${THEME_INDEX.reduce((n, g) => n + g.verses.length, 0)} ayat yang paling sering dicari orang. Bukan daftar lengkap — kalau temanya tidak ada di sini, coba tanya lewat obrolan.</p>
      </header>

      <ul class="theme-list">
        ${THEME_INDEX.map(
          (g) => `
          <li>
            <a class="trow" href="#/tema/${slugify(g.theme)}">
              <span class="trow-name">${esc(g.theme)}</span>
              <span class="trow-count">${g.verses.length} ayat</span>
            </a>
          </li>`,
        ).join("")}
      </ul>
    </div>`;

  say(`${THEME_INDEX.length} tema tersedia.`);
}

/** One theme's verses, fetched from the same per-surah shards the reading surface already uses. */
export async function renderTheme(mount: HTMLElement, slug: string): Promise<void> {
  bindActs();
  clearReadCards();
  const group = bySlug(slug);

  if (!group) {
    mount.innerHTML = `
      <div class="surah-view">
        <div class="oops" role="alert"><p>Tema itu tidak ada.</p></div>
        <div class="back-bottom">${backEl()}</div>
      </div>`;
    say("Tema tidak ditemukan.");
    return;
  }

  mount.innerHTML = `
    <div class="surah-view">
      <header class="surah-head">
        ${backEl()}
        <div class="surah-title">
          <p class="surah-tl">${esc(group.theme)}</p>
          <p class="surah-meta">${group.verses.length} ayat</p>
        </div>
      </header>
      <div class="verses" id="theme-verses"></div>
      <div class="back-bottom">${backEl()}</div>
    </div>`;

  const container = mount.querySelector<HTMLDivElement>("#theme-verses");
  if (!container) return;

  say(`${esc(group.theme)} — memuat ${group.verses.length} ayat.`);

  // Sequential, not Promise.all — each ayah paints as soon as it's ready instead of the whole
  // theme waiting on its slowest fetch, and it never issues more than one request at a time.
  for (const v of group.verses) {
    const meta = surahMeta(v.surah);
    try {
      const ayah = await loadAyah(v.surah, v.ayah);
      const card: VerseCard = {
        ...fromShard(ayah, v.surah, meta?.tl ?? `Surah ${v.surah}`),
        why: v.why,
        lazyTafsir: true,
      };
      registerReadCard(card);
      container.insertAdjacentHTML("beforeend", verseEl(card));
    } catch (err) {
      const msg = err instanceof ShardError ? err.message : `Gagal memuat ${v.ref}.`;
      container.insertAdjacentHTML("beforeend", `<div class="oops" role="alert"><p>${esc(msg)}</p></div>`);
    }
  }

  say(`${esc(group.theme)} — ${group.verses.length} ayat dimuat.`);
}
